Added support for MS5837 pressure sensor
PX4/PX4-Autopilot pull request #14869
Opened 2020-05-08 10:31 UTC by OskarPepryk

**Describe problem solved by this pull request**
Added support for MS5837 30bar pressure sensor used in underwater vehicles. With recent changes to PX4 UUV compatibility this seems like a desired feature.

**Describe your solution**
MS5837 has roughly identical interface as MS5611 sensor. The only difference is measurement compensation arithmetic. MS5837 support was included in ms5611 driver.

I have created a new sensor type definition DRV_BARO_DEVTYPE_MS5837 = 0x90, this can be changed if needed.

**Describe possible alternatives**
Moving underwater pressure sensors to separate driver module. Hydrostatic pressure needs to be converted to depth using different equations to those in vehicleAirData.cpp.

**Test data / coverage**
Tested using single MS5837 on Pixhawk Cube 2.1 on external I2C2 bus. Onboard MS5611 sensors keep working. I used a modifiec rc.board_sensors script to test the sensors, as well as running driver manually from nsh.

![Zrzut ekranu z 2020-05-08 12-24-39](https://user-images.githubusercontent.com/23101737/81397078-e7aed180-9126-11ea-85a9-3abf311cd1c2.png)

2020-05-08 14:06 UTC, dagar commented
I was wondering about having this as a standalone ms5837 driver (i2c only). Single drivers that support multiple types end up being a little convoluted, so architecturally we're working towards refactoring things such that having separate drivers for ms5611, ms5607, and ms5837 really wouldn't be a burden. 

Then in all system monitoring, console interation (https://github.com/PX4/Firmware/issues/14867), perf counters, etc there's no potential confusion.

2020-05-08 14:56 UTC, OskarPepryk commented
> 
> 
> I was wondering about having this as a standalone ms5837 driver (i2c only). Single drivers that support multiple types end up being a little convoluted, so architecturally we're working towards refactoring things such that having separate drivers for ms5611, ms5607, and ms5837 really wouldn't be a burden.
> 
> Then in all system monitoring, console interation (#14867), perf counters, etc there's no potential confusion.

This sounds good.  It's unlikely that anyone would use MS5837 for flying vehicles . Water depth calculation would require more changes to ms5611 driver anyway.

2021-01-31 15:07 UTC, dagar requested changes
Could you please split this off as a standalone ms5837 driver? Most flight controllers (multicopter, fixedwing, etc) will never use this so I'd prefer to only carry it for the underwater cases.

2021-02-10 16:50 UTC, mrpollo commented
@OskarPepryk are you still interested in merging this PR, please get in touch

2022-02-12 19:44 UTC, dagar commented
MS5837 support merged into master https://github.com/PX4/PX4-Autopilot/pull/18213.

2022-02-12 19:44 UTC, closed without merging