[VTOL] impose minimum transition duration
PX4/PX4-Autopilot pull request #15080
Opened 2020-06-10 16:42 UTC by ThomasRigi

**Describe problem solved by this pull request**
Before this PR, VT_F_TR_OL_TM would silently reduce VT_TRANS_MIN_TM when VT_F_TR_OL_TM was smaller. This almost caused a crash on our quadplane because the (non-airspeed) transition was considered finished way too early. The drone lost 45m of altitude before the quadchute could stabilise it (luckily we transitioned at 50m altitude). 

**Describe your solution**
Increase the open loop transition duration if it is smaller than the minimum transition duration and notify the user.

**Test data / coverage**
gazebo standard vtol: Log showing logged messages and imposed 10s front transition: https://logs.px4.io/plot_app?log=4204093e-ffbc-4c4a-b029-21cf52a55c17

2020-06-11 11:14 UTC, sfuhrer commented on src/modules/vtol_att_control/vtol_att_control_main.cpp
> +	if (_params.front_trans_time_openloop * 0.9f < _params.front_trans_time_min) {
```suggestion
	if (_params.front_trans_time_openloop < _params.front_trans_time_min * 1.1f) {
```

2020-06-11 11:25 UTC, sfuhrer requested changes
I don't think it will work as expected after this change, as for the airspeed-less transition it currently only looks at the value of the `front_trans_time_min` 
https://github.com/PX4/Firmware/blob/ab060cdab076fb6934a86a75349cd9330c873432/src/modules/vtol_att_control/standard.cpp#L179
Before, the trans min time was set to 0.9 of the openloop time, so it finished at 0.9*openloop time (also an incorrectness..). `front_trans_time_openloop` isn't used anywhere else.
So I guess there are some more changes required. I've had this on my todo since too long now, but given that the recent crash showed some real parameter issues I could try to higher its priority.

2020-06-11 11:54 UTC, ThomasRigi commented
The purpose of this PR is to make sure that the minimum transition time is not silently shortened by some other mostly unused parameter. Here I'm not proposing to change the airspeedless transition logic. Even though that's something that should probably be tackled too, if only for the sake of being more consistent between tiltrotors and quadplanes (and tailsitters). But that would be for another PR.

2020-06-12 08:26 UTC, sfuhrer commented
Okay, this PR is good to go in then. But we really should fix the logic as well, as it's a clear bug to me that `front_trans_time_min` instead of `front_trans_time_openloop` is used for the transition time in airspeed less mode.

2020-06-12 08:26 UTC, sfuhrer approved these changes

2020-07-03 17:19 UTC, merged