Enable offboard acceleration setpoints
PX4/PX4-Autopilot pull request #15707
Opened 2020-09-08 21:02 UTC by Jaeyoung-Lim

**Describe problem solved by this pull request**
When sending acceleration setpoints as part of offboard position setpoints as part of [SET_POSITION_TARGET_LOCAL_NED](https://mavlink.io/en/messages/common.html#SET_POSITION_TARGET_LOCAL_NED) mavlink message, the vehicle would not take off.

The reason seems to be that a downward acceleration was being copied while the vehicle was in `flying_but_ground_contact=true` state.  

**Describe your solution**
This PR adds the following.
- Enables a acceleration triggered takeoff based on the acceleration setpoint
- Fixes the takeoff logic so that the vehicle is able to take off while acceleration setpoints are being sent

**Test data / coverage**
Having acceleration setpoints do seem to improve the performance of trajectory tracking.
The below examples show a log of the vehicle tracking a circular trajectory.

- Without Acceleration feedforward setpoints: https://review.px4.io/plot_app?log=3f8f3643-991b-435e-8286-289aa2920803
![image](https://user-images.githubusercontent.com/5248102/92527345-249aea00-f227-11ea-9b63-0b526ac297d2.png)

- With Acceleration feedforward setpoints: https://review.px4.io/plot_app?log=7515c5b1-bfc1-4026-9a11-8eabda5134c0
![image](https://user-images.githubusercontent.com/5248102/92527377-311f4280-f227-11ea-8983-cf28ee816341.png)

**Additional context**
- Acceleration feedforward control was added in https://github.com/PX4/Firmware/pull/14212, but was not functional for offboard control.

2020-09-08 21:59 UTC, mhkabir approved these changes

2020-09-10 08:51 UTC, MaEtUgR requested changes
With this change no multicopter can land anymore!
It's a workaround and we need to find the root cause why ground contact stays with upwards acceleration.
Thanks @Jaeyoung-Lim for having a look at this!

2020-09-10 08:59 UTC, MaEtUgR commented
After discussion we came to the conclusion that probably the vertical acceleration trips the takeoff ramp because it's designed based on velocity and I didn't have time to fully adapt it to the acceleration possibilities. We need to track that down and in the short term @Jaeyoung-Lim can try using only horizontal acceleration feed-forward. I'd like to have a very minimal example to run locall such that I can get in this state because I then expect it will be easy for me to find the problem.

2020-09-13 23:31 UTC, dagar commented on src/lib/flight_tasks/tasks/FlightTask/FlightTask.cpp
> +		acceleration_triggered_takeoff = _acceleration_setpoint(2) < -0.3f;
Can you document this magic number?

2020-11-27 07:54 UTC, Jaeyoung-Lim commented
@MaEtUgR I fixed the issue now, can you review again?

2020-11-30 15:41 UTC, MaEtUgR commented
@Jaeyoung-Lim Good find! I did not find this when we were debugging before.
The main things to check are:
- Is the flag offboard only
- Is there a mode that erroneously sends acceleration that would take off assuming the base task only looks at velocity. Then we need to fix that task to not have unexpected takeoffs.
I'll quickly check.

2020-11-30 15:49 UTC, Jaeyoung-Lim commented
> - Is the flag offboard only

Yes! Since the climbout mode was being set in offboard mode flags

> Is there a mode that erroneously sends acceleration that would take off assuming the base task only looks at velocity. Then we need to fix that task to not have unexpected takeoffs.

That is something I would like to check, but as of now I think the only way to use acceleration setpoints are through feedforward and not as a standalone.

It could be problematic if they don't set the acceleration ignore flag when sending `SET_TARGET_POSITION_LOCAL_NED` since if you set the `type_mask=0` it will enable all setpoints. However this is a problem in the mavlink spec so the user is responsible to use this safely.

2020-12-02 16:06 UTC, MaEtUgR commented
> - Is the flag offboard only
> Yes! Since the climbout mode was being set in offboard mode flags

Got it, I double checked ✔️ 

> That is something I would like to check, but as of now I think the only way to use acceleration setpoints are through feedforward and not as a standalone.

Acceleration setpoints are supported internally as standalone, not just feed-forward. What's new with this pr is that you can actually trigger a takeoff with vertical acceleration setpoints only. I did not allow that before because I don't know what the velocity ramp ramps to. And I checked everything but the `SmoothVel` library to not publish any vertical acceleration setpoints that make it take off accidentally. After verifying also the `SmoothVel` library and the ramp we can merge.

2020-12-17 07:29 UTC, MaEtUgR commented
Like I feared the acceleration-based takeoff without dedicated handling in the takeoff ramp breaks auto takeoff. It immediately seems to trigger a takeoff on arm, land again and then takes off again. Since I didn't understand why exactly this happens it could still be unrelated but I did a quick bisect test and it seems to be that. Let me find out why this happens.
![image](https://user-images.githubusercontent.com/4668506/102456801-0ae91a00-4042-11eb-81f8-bf3b658d1f35.png)

2021-01-06 13:05 UTC, MaEtUgR commented
I moved the important part into a separate pr such that we can move on with it:
https://github.com/PX4/PX4-Autopilot/pull/16498

2021-01-06 15:18 UTC, Jaeyoung-Lim commented
@MaEtUgR Thanks!

2021-01-06 15:26 UTC, closed without merging

2021-01-06 19:41 UTC, MaEtUgR commented
I guess we do purely acceleration-based takeoffs in a different take then. We anyways discussed we need to move the takeoff logic into the tasks themselves such that they can decide when to do what and it should get easier to handle it then. In the meantime doing the takeoff by command or setting an upwards velocity setpoint to takeoff should do the trick.