fix empty log file "micrortps_bridge.log"
PX4/PX4-Autopilot pull request #15947
Opened 2020-10-12 15:49 UTC by oneWayOut

The log file **micrortps_bridge.log**   is empty if   make *_rtps  .
This PR is to fix this problem.

2021-01-17 13:17 UTC, TSC21 requested changes
Thanks! I was trying to recall why /dev/null was added but I think it was a remaining of a development iteration. A more correct way of doing this though is to silent the output when it is successful and show it when it fails. Can you please apply my suggestion instead? Thank you!

2021-01-17 13:17 UTC, TSC21 commented on src/modules/micrortps_bridge/micrortps_client/CMakeLists.txt
> +			>micrortps_bridge.log
```suggestion
			>micrortps_bridge.log 2>&1 || cat micrortps_bridge.log
```

2021-02-15 19:03 UTC, mrpollo commented
@TSC21 I'm taking over the suggestion so we can merge this

2021-02-15 19:26 UTC, mrpollo commented
@TSC21 This is now ready to merge, please go ahead :)

2021-02-15 19:27 UTC, TSC21 approved these changes

2021-02-15 19:28 UTC, merged