sensor calibration: apply board level adjustment to external sensors
PX4/PX4-Autopilot pull request #16127
Opened 2020-11-05 16:35 UTC by dagar

Potentially a quick interim solution for https://github.com/PX4/PX4-Autopilot/issues/16126.

2020-11-06 08:25 UTC, bresch approved these changes
I think this is a good solution until we get the optimal one.

2020-11-10 09:00 UTC, bresch requested changes
TODO: discuss with @priseborough

2020-11-10 09:27 UTC, priseborough approved these changes
This is the best we can do at the moment assuming that users will make an attempt to align external sensors with the autopilot.

2020-11-10 09:28 UTC, priseborough commented
I think FW users should be encouraged to use https://dev.px4.io/master/en/advanced/parameter_reference.html#FW_PSP_OFF ins tread of level to compensate for the pitch required to maintain height.

2020-11-12 00:19 UTC, Antiheavy commented
> I think FW users should be encouraged to use https://dev.px4.io/master/en/advanced/parameter_reference.html#FW_PSP_OFF instead of a level calibration to adjust the pitch/AoA required to maintain height.

I agree.

2020-11-12 12:32 UTC, bresch approved these changes

2020-11-12 15:37 UTC, merged