Update launch files to enable multi-video stream in SITL
PX4/PX4-Autopilot pull request #16497
Opened 2021-01-06 09:10 UTC by mzahana

**Describe problem solved by this pull request**
This PR complements PR https://github.com/PX4/PX4-SITL_gazebo/pull/687 in PX4_SITL_gazebo repo. This is to enable multi-video stream in SITL 

**Describe your solution**
Parameterizing the communication ports were required in order to differentiate the different streams from different MAVLink cameras, see PR https://github.com/PX4/PX4-SITL_gazebo/pull/687.

**Testing**
* Use this PR, and PR https://github.com/PX4/PX4-SITL_gazebo/pull/687, and then run [multi_uav_mavros_sitl.launch](https://github.com/mzahana/Firmware/blob/pr_multi_video_stream_sitl/launch/multi_uav_mavros_sitl.launch)
* Run QGroundcontrol. You should get the right video stream when you switch vehicles in QGC

2021-01-08 01:07 UTC, Jaeyoung-Lim requested changes
Could you also apply this to https://github.com/PX4/PX4-Autopilot/blob/master/Tools/gazebo_sitl_multiple_run.sh ?

2021-01-08 12:25 UTC, mzahana commented
> Could you also apply this to https://github.com/PX4/PX4-Autopilot/blob/master/Tools/gazebo_sitl_multiple_run.sh ?

@Jaeyoung-Lim  Done. Please check.

2021-01-08 18:29 UTC, Jaeyoung-Lim approved these changes
Tested on Ubuntu 20.04/Ubuntu Noetic and it works!

Thanks @mzahana !

2021-01-08 18:29 UTC, merged

2021-01-12 11:33 UTC, bonellia commented
Unfortunately, this prevents me to launch using /launch/single_vehicle_spawn.launch on Uubuntu 18.04 melodic.