Add support for 3D thrust setpoints for offboard attitude control
PX4/PX4-Autopilot pull request #16994
Opened 2021-02-28 20:21 UTC by Jaeyoung-Lim

**Describe problem solved by this pull request**
With the recent developments of control allocation and UUVs and also fully actuated systems, there needs to be a way to conveniently set 3D thrust setpoints when developing controllers.

Offboard mode provides an interface for this, but the interface for setting 3D setpoints were missing in the `SET_ATTITUDE_TARGET` mavlink message

**Describe your solution**
This PR adds support for `thrust_body` where 3D thrust setpoints in the body frame can be set by the new mavlink extension. 

**Test data / coverage**
This has been tested with the generated mavlink v2 header library, and works as intended

**Additional context**
- This PR is written on top of https://github.com/PX4/PX4-Autopilot/pull/16739
- This requires the mavlink PR to be merged
- @DanielDuecker @Zarbokk FYI

2021-02-28 21:50 UTC, dagar commented
Looks good to me. When you're ready we can merge into https://github.com/PX4/PX4-Autopilot/pull/16739 if still waiting on https://github.com/PX4/PX4-Autopilot/pull/16869.

2021-03-01 06:43 UTC, Jaeyoung-Lim commented
@dagar Thanks! Since this requires the PR in mavlink to be merged, I will include it once it is merged in mavlink

2021-03-02 08:35 UTC, weixuanzhang commented
Wouldn't it be useful if the torque command is also included in fully-actuated UUV?

2021-03-02 09:30 UTC, Jaeyoung-Lim commented
Hi @weixuanzhang !

Sorry if I am misunderstanding your comment, but this PR is not related to the UUV attitude control. This PR only adds a offboard interface that lets you set 3D thrust setpoints for "attitude" setpoints.

-  You can already send torque setpoints in offboard mode, with the `SET_ACTUATOR_CONTROL_TARGET` mavlink message: https://mavlink.io/en/messages/common.html#SET_ACTUATOR_CONTROL_TARGET

- If your comments are on fully actuated systems in general, UUV does not have a proper fully actuated implementation(yet). However, we already have a control allocation scheme for torque and thrust in https://github.com/PX4/PX4-Autopilot/pull/16528 / https://youtu.be/xjLM9whwjO4 for VTOL vehicles, and that could be used for fully actuated systems.

Would this answer your question?

2021-03-25 07:59 UTC, Jaeyoung-Lim commented
Included the mavlink update in this PR

2021-03-30 11:40 UTC, Jaeyoung-Lim commented
@dagar Should be ready to go!

2021-03-30 20:39 UTC, Jaeyoung-Lim commented
Now it seems good :sunglasses:

2021-03-31 12:31 UTC, LorenzMeier requested changes
Needs changes.

2021-03-31 12:31 UTC, LorenzMeier commented on src/modules/mavlink/mavlink_receiver.cpp
> +				attitude_setpoint.thrust_body[0] = attitude_setpoint.thrust_body[0];
This statement has no effect - could you please change it to the intended statement?

2021-03-31 21:34 UTC, Jaeyoung-Lim commented
@LorenzMeier Thanks for the catch! Fixed!

2021-04-01 11:57 UTC, LorenzMeier approved these changes

2021-04-01 11:58 UTC, merged