mc_pos_control: allow feed-forward offboard velocity control
PX4/PX4-Autopilot pull request #17261
Opened 2021-03-29 09:10 UTC by julianoes

This fixes feed-forward velocity input for offboard control where both velocity and position are set.
Without this change, the drone would just assume the requested position setpoint with the maximum velocity as specified by the parameters.

Fixes https://github.com/mavlink/MAVSDK-Python/issues/327.

2021-03-29 10:10 UTC, bresch requested changes
No, this removes the feedforward

2021-03-30 08:32 UTC, julianoes commented
@bresch your blunt answer is not really helpful. Please elaborate.

Without this change iris flies at speeds of 5 m/s to the position requested even if the feed-forward is set to 1 m/s. With this change the drone flies at 1 m/s as requested.

2021-03-30 08:37 UTC, julianoes commented
@bresch do we need a check for "if offboard or not"?

2021-03-30 09:44 UTC, bresch commented
> @bresch your blunt answer is not really helpful. Please elaborate

Sorry for that. Basically you changed an addition ("add if not nan") by an affectation ("set if nan"). Since the feedforward was added using this function, it isn't doing that anymore.

To fix that, you can:
1. leave `addIfNotNan` and add your `setIfNan` just below
2. modify `addIfNotNan` as follows:
```
void addIfNotNan(float &setpoint, const float addition)
{
	if (PX4_ISFINITE(setpoint) && PX4_ISFINITE(addition)) {
		// No NAN, add to the setpoint
		setpoint += addition;

-	} else if (!PX4_ISFINITE(setpoint)) {
+	} else if (!PX4_ISFINITE(setpoint) && PX4_ISFINITE(addition)) {
		// Setpoint NAN, take addition
		setpoint = addition;
	}

	// Addition is NAN or both are NAN, nothing to do
}
```
And swap the arguments in _positionControl():
```
-	ControlMath::addIfNotNanVector3f(_vel_sp, vel_sp_position);
+	ControlMath::addIfNotNanVector3f(vel_sp_position, _vel_sp);
```

I think 2. is the cleanest. What do you think @MaEtUgR ?

2021-03-30 09:53 UTC, julianoes commented
According to @MaEtUgR the current behavior is correct. The velocity setpoint is only supposed to be a feed-forward and *NOT* a limit.

2021-03-30 09:53 UTC, closed without merging