Commander: baro check: only report failure of mandatory instances
PX4/PX4-Autopilot pull request #17277
Opened 2021-03-31 08:30 UTC by RomanBapst

2021-03-31 11:47 UTC, bresch reviewed
I don't really get why there is this line
```
report_fail = false; // only report the first failure
```
`report_fail` is scoped inside the loop and will get overwritten at the next iteration

2021-03-31 11:49 UTC, bresch requested changes

2021-03-31 11:49 UTC, bresch commented on src/modules/commander/Arming/PreFlightCheck/PreFlightCheck.cpp
> +			bool report_fail = (required && report_failures && !baro_fail_reported);
you can then change the `if (required)` below to `if (report_fail)`. It makes the logic clearer.

2021-04-12 13:26 UTC, dagar commented
> I don't really get why there is this line
> 
> ```
> report_fail = false; // only report the first failure
> ```
> 
> `report_fail` is scoped inside the loop and will get overwritten at the next iteration

Yes that's a bit weird and the pattern is repeated in some of the other checks. Let's just get this in and revisit the entire reporting with the events interface.

2021-04-12 13:27 UTC, merged