Accumulated gyro filter fixes and improvements
PX4/PX4-Autopilot pull request #17647
Opened 2021-05-25 16:42 UTC by dagar

See commits for details.

##### Baseline (fake IMU sine sweep ramping to 100 Hz over 10 seconds)
![Screenshot from 2021-05-25 13-57-09](https://user-images.githubusercontent.com/84712/119545727-20850d00-bd61-11eb-8e45-ab896478591a.png)

#####  ESC dynamic notch filtering enabled (with intentional gaps in data at different points for testing resets and timeouts)
![Screenshot from 2021-05-25 13-59-45](https://user-images.githubusercontent.com/84712/119546073-7fe31d00-bd61-11eb-916a-c2ae9f59e8be.png)

##### FFT dynamic notch filtering enabled (still too much latency in the FFT peak detection, but more to come)
![Screenshot from 2021-05-25 13-55-06](https://user-images.githubusercontent.com/84712/119545463-d734bd80-bd60-11eb-89e8-5c8f06b608c5.png)

2021-05-25 18:11 UTC, dagar commented
I'm working on moving the `gyro_fft` to a sliding DFT and away from CMSIS entirely, but it's not quite ready yet. This will improve the output rate considerably.

2021-05-27 09:01 UTC, bresch requested changes

2021-05-27 14:15 UTC, dagar commented
New idea with filters
 - be paranoid checking that everything is finite during filter parameter change or reset
 - move finite checks out of filter updates entirely (they're not free and this is a hot path)
 - push finite checks out to users where we're not sure
      -  for example we're not going to get NANs in the expensive sensor_gyro_fifo case

Thoughts?

2021-05-27 17:00 UTC, dagar commented
I've updated the NotchFilter such that changes to only the notch frequency will be gradually applied, shifting it no more than half the bandwidth per filter update.

2021-05-28 08:31 UTC, bresch commented
> New idea with filters
> - be paranoid checking that everything is finite during filter parameter change or reset
> - move finite checks out of filter updates entirely (they're not free and this is a hot path)
>  - push finite checks out to users where we're not sure
        - for example we're not going to get NANs in the expensive sensor_gyro_fifo case

Yes, I'm fine with that

2021-05-30 22:05 UTC, dagar commented on src/lib/mathlib/math/filter/NotchFilter.hpp
> +			samples[n] = apply(samples[n]);
After some quick profiling I'd say it's a bit questionable if there's potential for larger jumps in notch frequency. Updating parameters for only one NotchFilter in an iteration is quite expensive, and there are quite a few of them potentially active.

Updated to instead reset each filter if the notch frequency shifts by more than the bandwidth.

2021-05-31 09:47 UTC, bresch approved these changes

2021-05-31 14:26 UTC, merged