sensors/vehicle_magnetometer: apply current compensation regardless of arming state
PX4/PX4-Autopilot pull request #17679
Opened 2021-05-31 16:38 UTC by dagar

Some systems have enough current (digital radios, companion computers, etc) when disarmed for this to matter.

@baumanta

2021-06-01 08:22 UTC, bresch requested changes

2021-06-01 08:22 UTC, bresch commented on src/modules/sensors/vehicle_magnetometer/VehicleMagnetometer.cpp
> +				// _actuator_controls_0_sub = uORB::Subscription{ORB_ID(actuator_controls_0)};
Maybe comment that we're already subscribing to it by default instead of this.

2021-06-01 08:22 UTC, bresch commented on src/modules/sensors/vehicle_magnetometer/VehicleMagnetometer.cpp
> +			if (mag_comp_typ == MagCompensationType::Current_inst0) {
Use a `switch-case` ?

2021-06-01 08:22 UTC, bresch commented on src/modules/sensors/vehicle_magnetometer/VehicleMagnetometer.cpp
> +		if (_armed && (_mag_comp_type == MagCompensationType::Throttle)) {
Turn into `switch-case` to make it nicer to read

2021-06-02 13:40 UTC, dagar commented on src/modules/sensors/vehicle_magnetometer/VehicleMagnetometer.cpp
> +			if (mag_comp_typ == MagCompensationType::Current_inst0) {
Done.

2021-06-03 11:51 UTC, bresch approved these changes

2021-06-03 14:08 UTC, merged