Broadcom AFBR-S50 Distance Sensor Driver: Test API
PX4/PX4-Autopilot pull request #17815
Opened 2021-06-28 20:34 UTC by samchamberlin

**Describe problem solved by this pull request**
This PR for the Broadcom AFBR-S50 Distance Sensor driver enables execution of a series of tests in order to verify the HAL implementation.

**Describe your solution**
The "test" arguement can be used within nutt shell for the afbrs50 driver in order to run the series of tests. Updated are printed out in the shell and delays were included to prevent breakpoint traps & faults.

**Test data / coverage**
The additions to the driver were tested successfully within the nutt shell on macOS and Linux.

**Additional context**

2021-06-28 21:15 UTC, AlexKlimaj requested changes

2021-06-28 21:15 UTC, AlexKlimaj commented on boards/ark/can-flow/init/rc.board_sensors
> +# afbrs50 start
Revert this file. We want the driver to start normally.

2021-06-28 21:15 UTC, AlexKlimaj commented on src/drivers/distance_sensor/broadcom/afbrs50/AFBRS50.cpp
> +>>>>>>> 3864c90f95 (added gate for processing distance measurements)
I think you have merge conflicts that need to be resolved.

2021-06-28 21:15 UTC, AlexKlimaj commented on src/drivers/distance_sensor/broadcom/afbrs50/AFBRS50.cpp
> +			_px4_rangefinder.set_min_distance(_min_distance);
Is this from your other PR?

2021-06-28 21:15 UTC, AlexKlimaj commented on src/drivers/distance_sensor/broadcom/afbrs50/AFBRS50.cpp
> +			_px4_rangefinder.set_min_distance(_min_distance);
I think you need to rebase this PR from master.

2021-06-29 02:12 UTC, dagar commented
Awesome, I wasn't sure if we were going to pass the timing tests.

2021-06-29 16:04 UTC, AlexKlimaj commented
@samchamberlin run a "make format" and repush.

2021-07-02 01:03 UTC, mcsauder commented on src/drivers/distance_sensor/broadcom/afbrs50/AFBRS50.cpp
> +static int test(const uint8_t rotation)
These changes all look good to me, I just might be missing why this method needs to be static.

2024-04-10 15:46 UTC, closed without merging