Fix Orbit altitude not being followed
PX4/PX4-Autopilot pull request #18547
Opened 2021-11-01 17:48 UTC by ThomasDebrunner

**Describe problem solved by this pull request**

When commanding an Orbit at a certain altitude, the vehicle does not go to the commanded altitude but stays at the current altitude.

**Describe your solution**
The problem stemmed from the fact that the `FlightTaskOrbit` inherited from `FlightTaskManualAltitudeSmoothVel`. The parent class took ownership over the z-velocity, but not position. So in Orbit approach, the position setpoints set by `FlightTaskOrbit` were ignored. This PR changes the inheritance that `FlightTaskOrbit` directly inherits from `FlightTaskManualAltitude`. All smoothing is done directly in `FlightTaskOrbit`.

- For Orbit approach, the `PositionSmoothing` library smoothes the approach based on position target
- While in Orbit, the `VelocitySmoothing` library smoothes the manual altitude changes from sticks

This has the side-effect that now the full Orbit approach trajectory gets smoothed.

**Test data / coverage**
Tested in SITL, and X500 on Skynode

2021-11-02 09:28 UTC, bresch requested changes

2021-11-02 09:28 UTC, bresch commented on src/modules/flight_mode_manager/tasks/Orbit/FlightTaskOrbit.hpp
> +	float _orbit_radius;
```suggestion
	float _orbit_velocity{};
	float _orbit_radius{};
```

2021-11-02 09:28 UTC, bresch commented on src/modules/flight_mode_manager/tasks/Orbit/FlightTaskOrbit.cpp
> +bool circle_tangents_for_position(const Vector2f &center, float radius, const Vector2f &position, Vector2f &out1,
I don't see where this is used

2021-11-02 11:01 UTC, ThomasDebrunner commented
Thanks @bresch , resolved your comments

2021-11-02 12:41 UTC, bresch submitted a review, later dismissed

2021-11-03 08:43 UTC, MaEtUgR requested changes
While quickly reading through I found that changing the direction is broken.
I'll quickly check if there's anything else.

2021-11-03 08:43 UTC, MaEtUgR commented on src/modules/flight_mode_manager/tasks/Orbit/FlightTaskOrbit.cpp
> +		is_clockwise = radius > 0;
```suggestion
		float radius = command.param1;
		is_clockwise = radius > 0;
```
Otherwise it's always > 0

2021-11-03 08:43 UTC, MaEtUgR commented on src/modules/flight_mode_manager/tasks/Orbit/FlightTaskOrbit.cpp
> +
```suggestion
```

2021-11-03 08:43 UTC, MaEtUgR commented on src/modules/flight_mode_manager/tasks/Orbit/FlightTaskOrbit.cpp
> +
```suggestion
```

2021-11-03 08:43 UTC, MaEtUgR commented on src/modules/flight_mode_manager/tasks/Orbit/FlightTaskOrbit.cpp
> +
```suggestion
```

2021-11-03 08:43 UTC, MaEtUgR commented on src/modules/flight_mode_manager/tasks/Orbit/FlightTaskOrbit.cpp
> +
```suggestion
```

2021-11-03 08:55 UTC, MaEtUgR commented
I found during quick testing that accelerating and decelerating by stick can lead to large overshoots and two reaproaches because the first one is overshooting in the other direction
<img width="495" alt="Orbit_before" src="https://user-images.githubusercontent.com/4668506/140032100-f72102ee-fb43-4203-8c8a-dc39533cdc44.png">
<img width="434" alt="Orbit_after" src="https://user-images.githubusercontent.com/4668506/140032108-e9c21b92-edf7-4443-b6ab-b1a215bbe6bc.png">

2021-11-03 09:26 UTC, MaEtUgR commented on src/modules/flight_mode_manager/tasks/Orbit/FlightTaskOrbit.cpp
> +		is_clockwise = radius > 0;
Fixed in bd289cc and verified

2021-11-03 09:48 UTC, MaEtUgR commented on src/modules/flight_mode_manager/tasks/Orbit/FlightTaskOrbit.cpp
> +
d8f4425

2021-11-03 09:48 UTC, MaEtUgR commented on src/modules/flight_mode_manager/tasks/Orbit/FlightTaskOrbit.cpp
> +
d8f4425

2021-11-03 09:49 UTC, MaEtUgR commented on src/modules/flight_mode_manager/tasks/Orbit/FlightTaskOrbit.cpp
> +
d8f4425

2021-11-03 09:49 UTC, MaEtUgR commented on src/modules/flight_mode_manager/tasks/Orbit/FlightTaskOrbit.cpp
> +
d8f4425

2021-11-03 09:51 UTC, MaEtUgR commented
It seems the issue was just because it reapproached when radius tracking wasn't perfect during acc/deceleration by stick so increasing the acceptance radius a bit solved it: d97704f

2021-11-03 09:52 UTC, MaEtUgR approved these changes

2021-11-03 16:37 UTC, MaEtUgR approved these changes

2021-11-03 16:37 UTC, merged