Data link loss reaction also in manual modes if enabled
PX4/PX4-Autopilot pull request #18765
Opened 2021-12-01 14:20 UTC by MaEtUgR

**Describe problem solved by this pull request**
When a pilot flies:
- manually in position mode
- BVLOS
- conventional remote e.g. SBUS receiver
- tablet to running QGC and relies on either QGC telemetry or even a video feed

and then he loses the data link he's basically flying blind but there's no failsafe reaction even if he enables the data link loss failsafe using `NAV_DLL_ACT` because the data link is not considered a strict requirement.

**Describe your solution**
I enable executing the data link loss failsafe also in manual modes if it's enabled.
For the use case where the pilot takes over in a manual mode during the data link loss reaction I had to introduce a flag at least temporarily. I want to solve this by allowing an event based reaction in the state machine where in this case only if you lose data link a reaction gets triggered and not all the time while you're in a mode and have no data link.

**Describe possible alternatives**
See last sentense above. It definitely needs improvements.

**Test data / coverage**
This was tested in simulation, in SIH with a lot of cases and flown in real world.

2021-12-01 14:37 UTC, dagar commented
I think this is fine if it can be separately enabled/disabled and it's off by default. By default we should never yank control away from a pilot that's operating.

2021-12-01 14:37 UTC, ThomasDebrunner approved these changes

2021-12-01 14:37 UTC, dagar requested changes
I don't think this is a safe default.

2022-10-26 11:32 UTC, MaEtUgR commented
This pr got obsolete with https://github.com/PX4/PX4-Autopilot/pull/20172
I think the idea of it is also covered with the new failsafes.

2022-10-26 11:32 UTC, closed without merging