ekf2: consolidate and simplify gnd effect logic
PX4/PX4-Autopilot pull request #18868
Opened 2021-12-16 21:02 UTC by dagar

I found the ekf2 gnd effect logic a bit convoluted and hard to follow with the somewhat awkward interaction where internal EKF state is updated when assembling publishing estimator output. This is an attempt to make it a little simpler by pushing it entirely into the the EKF backend.

Some of the logic is not identical, so might be worth a more careful review/discussion.

2021-12-17 09:20 UTC, bresch requested changes

2021-12-17 15:22 UTC, dagar commented on src/modules/ekf2/EKF/ekf_helper.cpp
> +			_control_status.flags.gnd_effect = (height < _params.gnd_effect_max_hgt);
That was intentional, the idea being the timeout would only apply to the "manually" set gnd effect flag. So if terrain estimate became invalid you could still be in gnd effect if within the timeout (10s) of the external ground effect setting (takeoff, etc).

You think a 10 second timeout should still apply to terrain validity?

2021-12-17 15:23 UTC, dagar commented on src/modules/ekf2/EKF/ekf.h
> +		if (!isTerrainEstimateValid()) {
This was a last minute addition, the other idea was set_gnd_effect_flag() could simply enable it, then only the timeout would disable.

2021-12-17 18:41 UTC, dagar commented on src/modules/ekf2/EKF/ekf.h
> +		if (!isTerrainEstimateValid()) {
How about the updated commit? https://github.com/PX4/PX4-Autopilot/pull/18868/commits/f482e39b2ba9f7a25cb2c2fb196ec805a9b598a2

 - the frontend can manually set gnd_effect based on external factors (like takeoff spool up) and it's disabled automatically after timeout
 - the backend terrain estimate always takes precedence

2022-01-03 08:24 UTC, bresch commented on src/modules/ekf2/EKF/ekf.h
> +		if (!isTerrainEstimateValid()) {
> How about the updated commit? f482e39

Yes, I find it much more understandable

2022-01-03 08:27 UTC, bresch commented on src/modules/ekf2/EKF/ekf_helper.cpp
> +			_control_status.flags.gnd_effect = (height < _params.gnd_effect_max_hgt);
Ok, no, I think this is fine

2022-01-03 15:22 UTC, dagar commented
Conflicts with master resolved and rebased.

2023-03-09 15:57 UTC, dagar commented
A lot of the relevant cleanup here happened along with moving the status flags to the delayed time horizon. https://github.com/PX4/PX4-Autopilot/pull/20576

2023-03-09 15:57 UTC, closed without merging