WIP ekf2: enable initialization without baro data
PX4/PX4-Autopilot pull request #20021
Opened 2022-08-08 15:10 UTC by bresch

- Pass initialization when no baro data is available and when baro fusion is disabled (`EKF2_BARO_CTRL` = 0)
- Add fake height fusion when no vertical aiding is available

TODO:
- [ ] review vertical position validity flag

2022-08-30 09:29 UTC, priseborough commented on src/modules/ekf2/EKF/fake_height_control.cpp
> +	const float obs_var = sq(0.5f);
We should use the existing baro noise parameter for this to facilitate tuning for different use cases, eg rover vs boat in swells

2022-08-30 09:33 UTC, priseborough reviewed
All good from my review, but we should make the observation noise tuneable which could be done using the baro parameter. We would need to update parameter tuning notes to make this clear.

2022-08-31 11:31 UTC, bresch commented
@priseborough We apparently already have a parameter for this: https://github.com/PX4/PX4-Autopilot/pull/20021/commits/8d1c38d7555ed78302d653502a44d2dd420a2c0a

2022-09-01 04:57 UTC, priseborough submitted a review, later dismissed

2022-09-01 14:12 UTC, dagar commented
Rebased to resolve merge conflict (csv auto commit) and it's now broken due to `_time_last_imu` usage. I'll update the branch.

2022-09-01 14:32 UTC, dagar commented on src/modules/ekf2/EKF/fake_height_control.cpp
> +		resetEstimatorAidStatus(_aid_src_fake_pos);
This is problematic because it's going to reset things for x & y as well.

2022-09-01 14:38 UTC, dagar requested changes
The sharing of `_aid_src_fake_pos` is potentially problematic. Not a big deal for fake pos/hgt, but we should still try to get it right.

Personally I would either split _aid_src_fake_pos for pos and hgt, or do a bit more to merge the routines (like merging fuseFakeHgt() and fuseFakePosition(). You could still have separate state machines for enabling/disable fake pos/hgt, but ultimately the fusion and updating _aid_src_fake_pos would be centralized and happen together. 

Keeping fake height completely separate also seems fine if that's what you'd prefer.

2022-09-01 15:01 UTC, dagar commented on src/modules/ekf2/EKF/ekf.h
> +	bool _using_synthetic_hgt{false};	///< true if we are using a synthetic height to constrain drift
Any reason we don't expose these as control status flags?

2022-09-08 15:36 UTC, bresch commented
@dagar 
- The "fake position" and "fake height" are now completely separate. Even if it sounds "nice" to have them together, it makes the logic less readable and less "standard".
- The en-/disabled flags for fake pos/hgt are now part of `_control_status.flags`
- The baro sample is popped out the baro buffer in `controlBaroHeightFusion`, used in place and **not** stored as `_baro_sample_delayed` anymore.
- Baro data isn't used in `initialiseFilter` anymore

2022-09-10 16:27 UTC, dagar approved these changes

2022-09-10 16:29 UTC, merged