Reset rate integral in acromode
PX4/PX4-Autopilot pull request #20486
Opened 2022-10-26 08:03 UTC by Jaeyoung-Lim

## Describe problem solved by this pull request
In acromode, the yaw integral can become large since the vehicle can have aero dynamic forces that try to stabilize the vehicle

## Describe your solution
Discussed in the FW dev call, resetting integrals in acro mode

## Describe possible alternatives
- we could also try to only reset the yaw integral and keep the others

## Test data / coverage
- Tested in SITL: https://review.px4.io/plot_app?log=f2fd0b16-92fc-4308-b19f-a9d6a789e1a4
The integrals are reset in acro modes

## Additional context
- This topic was discussed in the fw dev call: https://discuss.px4.io/t/fw-vtol-call-october-25-2022/29505

2022-10-26 14:49 UTC, sfuhrer commented
Wasn't the original intend as discussed in the FW devcall to only reset the integral (ideally only yaw) on mode changes? The proposal here disables all integral action in all axes in Acro, no?

I still wonder we how could tackle this at the root. In Acro it will now always yaw in the opposite direction of roll, and the reason I think it was okay till now is that the default max I gain (FW_YR_IMAX) was only 0.2, now though it's increased to 0.4, and thus we need to think about further fixes. Maybe disabling the integrator completely (like here but only on yaw) is better than the current state.
![image](https://user-images.githubusercontent.com/26798987/198053215-e16d9831-30b7-4cab-a105-0952a9db3cd9.png)

2022-11-02 14:31 UTC, tstastny commented
> Just note: I still want to come up a conclusion on what is the actual source of the yaw rate integrator wind up in acro mode. I still have my doubts that it's from adverse yaw.

It doesnt even need to be adverse yaw. just any flight condition with incompatible acro commands. when a yawrate command comes in that is not physically possible, the error will integrate, because the controller cant change physics.

2022-11-23 20:05 UTC, chris1seto commented
As per the fixed wing meeting yesterday,

I have the following logs (originally posted to discord) showing how the yaw integral behaves in acro mode, after being auto tuned:

# 1: https://review.px4.io/plot_app?log=223a6fae-8386-41c9-a5c8-2569e8a457fb

# 2: https://review.px4.io/plot_app?log=f2dc1358-f026-4a1a-b23d-7196b7ae2964

The airplane is my turbo timber evolution, documented here: https://docs.px4.io/main/en/frames_plane/turbo_timber_evolution.html

During the call, I think I realized that I was thinking about this wrong, in that it's not the aerodynamic effects which are leading to the yaw integral winding up, it's the fact that the vehicle yaw value will change as a function of roll + pitch inputs, and the yaw integral would then track a position error, not a rate error. If the heading of the vehicle changes, then then will cause the yaw rate integral will always be wound up due to the position error. 

I think the best way to solve this is to simply not regulate yaw rate in acro at all (essentially, only pass FF), OR only try to regulate to P. This would mean that yaw will resist disturbances, but not resist steady state position changes. 

I was asked to provide flight test logs showing only enabling FF, then P. I'll be working on this in the next week or so.

2022-11-23 23:51 UTC, chris1seto commented
Attached is a log file with the integral and FF disabled. This felt really good in the air.  The P tuning came from the autotuner (with the integral and FF tuning from that tuning session set to 0)

https://review.px4.io/plot_app?log=ca45a36b-594e-434d-bd2b-ad756cfc7c82

At this point I think at most P + FF should only be enabled in acro mode. Possibly not even P, but it seems like it feels fine in the air.

2022-12-12 14:35 UTC, sfuhrer commented
On the yaw integrator issue: all data I saw so far indicate that it only appears at a significant amount in Acro mode, and thus that it is systematic (and totally expected with the controller trying to keep 0 yaw rate even in turns).
![image](https://user-images.githubusercontent.com/26798987/207071053-01d0e783-e9db-4975-a689-787fb243eb7e.png)

>At this point I think at most P + FF should only be enabled in acro mode. Possibly not even P, but it seems like it feels fine in the air.

Agree with you. You don't have the yawrate P very high, so it only slightly deflects the rudder in the "wrong" direction in tight turns (16%) Still, clean solution for me is to have yawrate not controlled at all in Acro mode by default, and possibly enabled to do so via a parameter (e.g. boolean FW_ACRO_YR_CTRL).
![image](https://user-images.githubusercontent.com/26798987/207071580-f61133a1-7d6a-4375-8dd8-550b6a953a2b.png)

2022-12-13 09:06 UTC, Jaeyoung-Lim commented
I will update the PR aligned with the discussion we had in the FW dev call

2022-12-16 11:44 UTC, Jaeyoung-Lim commented
I am putting an hold on this so that we can hopefully get https://github.com/PX4/PX4-Autopilot/pull/20237 in before this!

2023-02-02 14:27 UTC, sfuhrer requested changes
Generally reset all integrals in Acro seems wrong to me. As discussed, the clean solution would to either disable any yaw control in Acro and directly actuate the yaw actuators by the yaw stick, possibly with a parameter to bring back also yaw rate stabilization.
Or then to only disable the yaw integrator (but not roll and pitch).

2023-02-02 16:13 UTC, chris1seto commented
> Generally reset all integrals in Acro seems wrong to me. As discussed, the clean solution would to either disable any yaw control in Acro and directly actuate the yaw actuators by the yaw stick, possibly with a parameter to bring back also yaw rate stabilization. Or then to only disable the yaw integrator (but not roll and pitch).

I agree with all of this. Either of those two options would be fine baby steps. (in the future, the best improvement could possibly be FF + turn coordination being sent to yaw, but until then..)

2023-02-14 17:20 UTC, Jaeyoung-Lim commented
Added the long overdue changes of configurable integral resets, and yaw integral reset by default on yaw

Flight Log: https://review.px4.io/plot_app?log=7f7bbdaf-5e47-4fd8-95cd-189ce67376a3
![bokeh_plot (10)](https://user-images.githubusercontent.com/5248102/218810670-b1383fd8-8493-489e-8d24-96476f898772.png)

2023-02-14 19:14 UTC, sfuhrer commented
As discussed in the call before, let's change it to a boolean parameter and slightly adjust the param description (disable yaw vs. reset integrator) and this is good to go!

2023-03-14 12:19 UTC, Jaeyoung-Lim commented
@sfuhrer Changed parameter to boolean
- Flight log: https://review.px4.io/plot_app?log=6e593a18-92e7-458d-873a-a2577c4f6319
![bokeh_plot (4)](https://user-images.githubusercontent.com/5248102/224999126-ec7eb7dc-e765-4a48-95bf-ea8767d7905b.png)

2023-05-09 16:08 UTC, closed without merging