Add TI ina220 driver
PX4/PX4-Autopilot pull request #20504
Opened 2022-10-28 13:42 UTC by benjinne

## Describe problem solved by this pull request
Adds the INA220 driver

## Describe your solution
based on the INA226 driver

## Test data / coverage
Tested using an ina220 and validated current voltage readings were accurate compared to multi-meter

2022-11-03 21:35 UTC, benjinne commented
Hey let me know what I need to do for this @dagar

2022-11-04 13:36 UTC, dirksavage88 commented
Are you using a custom PCB/prototype for this? Or an evm that TI sells? I'm trying to find one but only see ina226 boards (Ali & banggood)

2022-11-04 13:44 UTC, benjinne commented
> Are you using a custom PCB/prototype for this? Or an evm that TI sells? I'm trying to find one but only see ina226 boards (Ali & banggood)

It's for a custom PDB I'm designing

2022-11-17 01:40 UTC, AlexKlimaj requested changes
Why change the drv_sensor values for the existing sensors?

2022-11-17 18:31 UTC, benjinne commented
> Why change the drv_sensor values for the existing sensors?

There wasn't any room left to add more so I separated out the power_devtypes to

2022-11-23 16:08 UTC, dagar commented on src/drivers/power_monitor/ina220/ina220.cpp
> + *   Copyright (c) 2019-2020 PX4 Development Team. All rights reserved.
```suggestion
 *   Copyright (c) 2022 PX4 Development Team. All rights reserved.
```

2022-11-23 16:08 UTC, dagar commented on src/drivers/power_monitor/ina220/ina220.h
> + *   Copyright (C) 2019 PX4 Development Team. All rights reserved.
```suggestion
 *   Copyright (C) 2022 PX4 Development Team. All rights reserved.
```

2022-11-23 16:08 UTC, dagar commented on src/drivers/power_monitor/ina220/ina220_main.cpp
> + *   Copyright (C) 2021 PX4 Development Team. All rights reserved.
```suggestion
 *   Copyright (C) 2022 PX4 Development Team. All rights reserved.
```

2022-11-23 16:08 UTC, dagar commented on src/drivers/power_monitor/ina220/ina220_params.c
> + *   Copyright (c) 2019, 2021 PX4 Development Team. All rights reserved.
```suggestion
 *   Copyright (c) 2022 PX4 Development Team. All rights reserved.
```

2022-11-23 20:10 UTC, dagar approved these changes

2022-11-23 20:11 UTC, dagar commented
Changing the sensor type is usually a bad idea, but in this case it's harmless.

2022-11-23 20:11 UTC, merged