Log position setpoint reference for fixedwings with NPFG
PX4/PX4-Autopilot pull request #20512
Opened 2022-10-30 20:38 UTC by Jaeyoung-Lim

## Describe problem solved by this pull request
A clear and concise description of the problem this proposed change will solve. Or, what it will improve.
E.g. For this use case I ran into...

## Describe your solution
This commit adds a state in the npfg library which keeps the position setpoint reference, so that it can be published as part of the `vehicle_local_position_setpoint` message.

This is useful to see how well the vehicle is tracking the reference

## Test data / coverage
Tested in SITL Gazebo
```
make px4_sitl gazebo_plane
```

**Before PR**

**After PR**

## Additional context
Add any other related context or media.

2022-11-16 17:14 UTC, tstastny requested changes
Nice idea to log this. A few corrections / comments. Also - @sfuhrer maybe you could comment on if publishing the local position setpoint topic doesnt interfere with e.g. multicopter control when the aircraft is a VTOL and running both controllers?

@Jaeyoung-Lim can you put a plot of the setpoint working for waypoint following as well after making these changes? -- just so we can see that it does what we think it does. There would be a jump most likely when switching from flying directly to waypoint to following line.

2022-11-16 17:14 UTC, tstastny commented on src/lib/npfg/npfg.hpp
> +	matrix::Vector2f position_setpoint_{matrix::Vector2f{NAN, NAN}};
I would either rename this the "closest point", or at least put that the "position setpoint" corresponds to the closest point from the vehicle on the path. Just to make a clear difference between "position setpoints" getting put in as waypoints.. and what the guidance law is actually projecting/tracking on the path.

```suggestion
	matrix::Vector2f closest_point_on_path_{matrix::Vector2f{NAN, NAN}}; // instantaneous position setpoint [m]
```

2022-11-21 18:52 UTC, Jaeyoung-Lim commented
@tstastny Thanks for the review and corrections!

Here is the log with a normal waypoint navigation: https://review.px4.io/plot_app?log=76b7eeaa-db7f-4813-ae06-d6cf32cad181
![bokeh_plot (9)](https://user-images.githubusercontent.com/5248102/203136288-91a918ab-ab37-4cda-90b7-b3da19b24389.png)
![bokeh_plot (8)](https://user-images.githubusercontent.com/5248102/203136291-1de8277e-31ac-4098-ba2a-7990cdbc393f.png)

2022-11-22 07:17 UTC, tstastny approved these changes

2022-11-22 07:19 UTC, merged

2022-11-22 09:39 UTC, sfuhrer commented
>Also - @sfuhrer maybe you could comment on if publishing the local position setpoint topic doesnt interfere with e.g. multicopter control when the aircraft is a VTOL and running both controllers?

I was also published before, so I don't see an issue.