vehicle_magnetometer: fix standalone mag bias est factored into in flight mag cal
PX4/PX4-Autopilot pull request #20543
Opened 2022-11-03 15:06 UTC by dagar

The preflight mag bias estimate is in the vehicle body frame and removed from the raw mag data after it's rotated, calibrated, etc.

The in flight mag bias (from ekf2) is in the vehicle body frame, but stored as a sensor frame offset immediately.

2022-11-03 15:10 UTC, dagar commented
I really don't like this interaction between the mag_bias_estimator and ekf2 mag bias, maybe consolidation would ultimately be a lot simpler.

2022-11-03 16:02 UTC, dagar commented
We really need to do more testing (and thorough log inspection) with non-zero board rotations and other sensors orientations.

2022-11-07 08:53 UTC, bresch requested changes
//

2022-11-07 08:55 UTC, bresch approved these changes

2022-11-07 14:31 UTC, merged

2022-11-07 14:32 UTC, dagar commented
Backported for v1.13.2. https://github.com/PX4/PX4-Autopilot/commit/872ac68dafb2a7e6f5ea03106f33c3745ffc185f