ekf2: on accel clipping immediately reset to GNSS vel/pos (if data is good)
PX4/PX4-Autopilot pull request #20574
Opened 2022-11-08 18:22 UTC by dagar

Accel clipping can still be quite a dangerous situation. Rather than waiting I think it would be better to immediately reset to GNSS vel/pos on frames where it's available and the data is good. With the specific GNSS quality checks and relatively low GNSS frequency (5-10 Hz) I don't think immediately resetting on any clipping will be too aggressive (the alternative is much worse).

If this works it might also make sense to expand to range height and baro height. So far I specifically didn't add this for EV as it's quite likely any VIO is also suffering (with worse reporting).

2022-11-08 18:42 UTC, mcsauder commented on src/modules/ekf2/EKF/ekf.cpp
> +		const Vector3f clipping_ef = _R_to_earth * clipping_bf;
With a minor change to this LOC, could you collapse this block into a for loop? (I don't know if that has a negative performance impact, you can speak to that.)  Nice work Daniel.

2022-11-08 18:42 UTC, mcsauder submitted a review, later dismissed
LGTM

2022-11-11 08:42 UTC, bresch reviewed
Continuously resetting the pos and vel to GPS would bypass any filtering and make the EKF really sensitive to any GPS spikes/jumps. Why not simply increase the accel process noise? This way the EKF can still work normally and will naturally follow the GPS more than the accel while still being resilient against GPS spikes.

2022-11-11 14:37 UTC, dagar commented
> Why not simply increase the accel process noise? 

We do, but it doesn't seem to be nearly enough.

https://github.com/PX4/PX4-Autopilot/blob/acd8f20a8563ed7d38754fdfb7a2c82712ea07ed/src/modules/ekf2/EKF/covariance.cpp#L222-L230

Look at how the z velocity (and then throttle) jumps. 

![Screenshot from 2022-11-11 09-25-10](https://user-images.githubusercontent.com/84712/201360059-7193001d-2148-432d-88cf-91ac61529243.png)


> Continuously resetting the pos and vel to GPS would bypass any filtering and make the EKF really sensitive to any GPS spikes/jumps.

I agree, but this is more of a last ditch effort to prevent the spike from reaching the controllers (possibly preventing even more clipping). The other thing to keep in mind is this will only possibly reset if we have clipping on the same frame as a GPS sample (eg 1 in 10 EKF updates) and GPS velocity quality is good and has been recently fused. So I wouldn't expect it to be a continuous reset, although maybe it could also be rate limited as a precaution (this is a bit hard to test for real).

2022-11-11 15:09 UTC, dagar commented
I updated the logic so that it can't reset continuously (3 sec timeout).

2022-11-15 10:46 UTC, bresch commented
> We do, but it doesn't seem to be nearly enough.
> Look at how the z velocity (and then throttle) jumps.

Are you sure this is caused by clipping? Usually when I've seen clipping affecting the vertical velocity, the counter went to several hundreds and the velocity error was still quite low (< 1m/s). With a clip counter of 12 I'm quite surprised that you're having issues.

2022-11-15 10:49 UTC, bresch requested changes
I'm not convinced yet that this is really required and would like to inspect the log showing the issue first. It might be that the existing logic is broken or that there is another issue.

2026-08-10 02:19 UTC, closed without merging