boards: added ThePeach K1/R1 Flight Controller
PX4/PX4-Autopilot pull request #20664
Opened 2022-11-24 02:54 UTC by ThePeach-kr

Dear PX4 Team,

We developed a Flight Controller.
I would like to add our K1/R1 Flight Controller code to the PX4-Autopilot.
Also, rebase on Nuttx 10.3+

Related PR
https://github.com/PX4/PX4-Autopilot/pull/20176

Thanks.

2022-11-24 14:00 UTC, junwoo091400 commented
Is this available for purchase online by any chance? Would you be interested in adding this board to the PX4 Documentation?

2022-12-05 11:32 UTC, davids5 requested changes
See change requests. 

As an aside question: How are R1 and K1 different? Gould it be one binary and uses runtime detection?

2022-12-05 11:32 UTC, davids5 commented on boards/thepeach/k1/nuttx-config/include/board.h
> +/* The PX4FMUV2 uses a 24MHz crystal connected to the HSE.
Name should be this HW

2022-12-05 11:32 UTC, davids5 commented on boards/thepeach/k1/nuttx-config/include/board.h
> + *   Copyright (C) 2009, 2016 Gregory Nutt. All rights reserved.
Add 2022

2022-12-05 11:32 UTC, davids5 commented on boards/thepeach/r1/nuttx-config/include/board.h
> + *   Copyright (C) 2009, 2016 Gregory Nutt. All rights reserved.
Add 2022

2022-12-05 11:32 UTC, davids5 commented on boards/thepeach/r1/nuttx-config/include/board.h
> +/* The PX4FMUV2 uses a 24MHz crystal connected to the HSE.
Name as this HW

2022-12-06 02:16 UTC, ThePeach-kr commented
> See change requests.
> 
> As an aside question: How are R1 and K1 different? Gould it be one binary and uses runtime detection?

R1 is integrated with Raspberry Pi CM3+, unlike K1. Other than this, there's no big difference.
but, There is no version detection pin, so it will be difficult to make it run as one binary.

Thank you.

2022-12-06 07:02 UTC, davids5 approved these changes

2022-12-06 11:43 UTC, merged

2022-12-13 09:26 UTC, ThePeach-kr commented
@hamishwillee 
I would appreciate it if you could add our boards to the sidebar!
I appreciate your work on this :smile: