Param when select is MTD_PARAMETERS query mtd for param location
PX4/PX4-Autopilot pull request #20805
Opened 2022-12-20 10:54 UTC by PetervdPerk-NXP

MTD_PARAMETERS can be freely defined as any path board the rcS script has to check all paths manually.

- /fs/mtd_params
- /dev/eeeprom0
- /mnt/qspi/params

This patch adds the MTD_PARAMETERS keyword to `param select` when MTD_PARAMETERS  is select the PX4 parameters system will query mtd for the parameter file path.

2022-12-20 10:58 UTC, davids5 requested changes
This is not the intent of how this is supposed to work.

2022-12-20 11:02 UTC, PetervdPerk-NXP commented
So what's the intent how it's supposed to work?
When there's a entry MTD_PARAMETERS defined you've got a path to store parameters locally right?
Problem is that it's only limited to the PX4 FRAM storage MTD driver, yet can also store it to a dedicated HW pheripheral S32K1XX EEPROM or a mounted filesystem, for S32K3 LittleFS @ /mnt/qspi

2022-12-20 11:35 UTC, davids5 commented
All the paths are legacy V2 or flexible with the mtd.cpp in the board fille. 

On can define mtd.cpp in the board support if the [default v2](https://github.com/PX4/PX4-Autopilot/blob/dff946c39a01b883fbd7967c8b9255ca02be826b/platforms/nuttx/src/px4/common/px4_mtd.cpp#L244-L282) mtd behavior (that is FRAM only) is not enough. Then the manifest (mft) can be queried See

https://github.com/PX4/PX4-Autopilot/blob/main/src/systemcmds/mft/mft.cpp

The usage in RC is determining if the Keys Subject and value are present.

The rest of the mounts are done by the system. The  mtd command can be used to. https://github.com/PX4/PX4-Autopilot/blob/main/src/systemcmds/mtd/mtd.cpp

I think your use case would be served by an mtd.cpp file and follow the naming convention for param. If not we can hop on a call and work it out.

2022-12-20 12:52 UTC, davids5 approved these changes
Ok this makes sense. Let's see if HW CI passes

2022-12-20 15:08 UTC, dk7xe commented
@PetervdPerk-NXP please rebase! See https://github.com/PX4/PX4-Autopilot/pull/20794#issuecomment-1359456573

2022-12-20 20:45 UTC, davids5 approved these changes
LGTM - What has CI so bent out of shape?

2022-12-21 08:14 UTC, PetervdPerk-NXP commented
@davids5 
HW Rack looking good but maybe needs a manual to on a FMU-V2 to be sure
http://px4-jenkins.dagar.ca:8080/blue/organizations/jenkins/PX4-Autopilot/detail/PR-20805/3/pipeline/382#step-389-log-44
http://px4-jenkins.dagar.ca:8080/blue/organizations/jenkins/PX4-Autopilot/detail/PR-20805/3/pipeline/1100#step-1101-log-43
http://px4-jenkins.dagar.ca:8080/blue/organizations/jenkins/PX4-Autopilot/detail/PR-20805/3/pipeline/1629#step-1630-log-42

2022-12-21 12:41 UTC, PetervdPerk-NXP commented
@davids5 Previous proposal broke backup/fallback mechanism.
Now I'm using a board specific override mechanism, is also a bit cleaner I think.

2022-12-21 12:57 UTC, davids5 approved these changes
@PetervdPerk-NXP - good catch and solution

2022-12-21 14:48 UTC, dagar commented
After the parameter server is in place (https://github.com/PX4/PX4-Autopilot/pull/20773) I was thinking of pushing more of this into kconfig and getting away from the brittle init script configuration of the parameter system. Let me know if you have any input.

2022-12-22 07:42 UTC, dk7xe commented
Logfile of driving around indoors yesterday - https://logs.px4.io/plot_app?log=0d0ab8ed-2c00-4c19-a6d1-8931975f00ae

2023-03-24 05:34 UTC, junwoo091400 commented
@dagar but for now it seems like this would be a good change to have in (we can accommodate to parameter server later), what do you think?

2023-07-25 21:14 UTC, junwoo091400 commented
During today's maintainers call, @dagar pointed out that directory where the flight log gets saved to should rather be a parameter to the user to set.

But this would be a good first step into having a more flexible data path in px4. Could we get this in since it's already approved?

2024-04-10 13:12 UTC, closed without merging