Support planes in Gazebo(gz)
PX4/PX4-Autopilot pull request #20939
Opened 2023-01-15 18:09 UTC by Jaeyoung-Lim

### Solved Problem
When ... I found that ...

Fixes #{Github issue ID}

### Solution
- Add ... for ...
- Refactor ...

### Alternatives
We could also ...

### Test coverage
- Unit/integration test: ...
- Simulation/hardware testing logs: https://review.px4.io/

### Context
Related links, screenshot before/after, video

2023-01-15 19:09 UTC, bperseghetti commented
Nice, I've worked on adding functionality to the joint position controller system to control groups as well as use subtopics that inherit the model name. I also made the Ackermann steering plugin behave the way we want it to allowing for phi (center steering angle published as a double)

2023-01-15 19:25 UTC, Jaeyoung-Lim commented
> Nice, I've worked on adding functionality to the joint position controller system to control groups as well as use subtopics that inherit the model name. I also made the Ackermann steering plugin behave the way we want it to allowing for phi (center steering angle published as a double)

Great! Is this somewhere I can use? or are you saying that this is already what I am using?

2023-01-15 20:18 UTC, bperseghetti commented
> > Nice, I've worked on adding functionality to the joint position controller system to control groups as well as use subtopics that inherit the model name. I also made the Ackermann steering plugin behave the way we want it to allowing for phi (center steering angle published as a double)
> 
> Great! Is this somewhere I can use? or are you saying that this is already what I am using?
> 
> > adding functionality to the joint position controller system to control groups
> 
> I would like to start separating motors(velocity control) and servos (joint control), but I think we need to make the distinction on the gz_bridge with control allocation first

Yep, that's what I'm working on. Haha 
Here is what we needed for Ackermann: https://github.com/gazebosim/gz-sim/pull/1860
Here is my work for multiple joint_name and sub_topic for joint-controller and joint-position-controller:
https://github.com/rudislabs/gz-sim/tree/pr-multi-joint-with-subtopic

I'll finish implementing the joint-controller later today, but the joint-position-controller works perfect.

2023-01-16 03:00 UTC, bperseghetti commented
@Jaeyoung-Lim @dagar Here is what will allow us to do multi-vehicle like what I enabled for the multicopter:
https://github.com/gazebosim/gz-sim/pull/1861
https://github.com/gazebosim/gz-sim/pull/1860

2023-01-16 13:03 UTC, ahcorde commented
When I execute 

```bash
make px4_sitl gz_x500
```

I got this error:

```bash
INFO  [dataman] data manager file './dataman' size is 7866640 bytes
INFO  [init] starting gazebo with world: /tmp/PX4-Autopilot/Tools/simulation/gz/worlds/default.sdf
WARN  [init] PX4_GZ_MODEL_NAME or PX4_GZ_MODEL not set using PX4_SIM_MODEL.
INFO  [gz_bridge] world: default, model name: plane_0, simulation model: plane
libEGL warning: DRI2: failed to create dri screen
libEGL warning: DRI2: failed to create dri screen
ERROR [gz_bridge] Service call timed out
ERROR [gz_bridge] Task start failed (-1)
ERROR [init] gz_bridge failed to start
ERROR [px4] Startup script returned with return value: 256
```

2023-01-16 14:20 UTC, ahcorde requested changes

2023-01-16 14:20 UTC, ahcorde commented on Tools/simulation/gz/models/plane/model.sdf
> +    <joint name='rudder_joint' type='revolute'>
```suggestion
    <joint name='px4_servo_4' type='revolute'>
```

2023-01-16 15:28 UTC, ahcorde commented
I merged with `main`, but I removed the merge and it's working. thank you

2023-01-16 15:37 UTC, Jaeyoung-Lim commented on Tools/simulation/gz/models/plane/model.sdf
> +    <joint name='rudder_joint' type='revolute'>
Thanks!

2023-01-24 14:20 UTC, dagar approved these changes

2023-01-24 14:21 UTC, dagar commented
Needs more work (tuning, Fortress support questions, etc), but this should be good enough to merge into main so we can continue iterating.

2023-01-24 14:22 UTC, merged