Rearrange npfg use path input
PX4/PX4-Autopilot pull request #21071
Opened 2023-02-06 09:49 UTC by KonradRudin

### Solved Problem
Rearranged the interaction between the FwPosController and npfg. the guidance logic should not be concerned with the waypoint triplets directly. The FwPosController converts the triplets into a path setpoint which is fed into the npfg navigation logic. This is part of separating the npfg into smaller controllers with cleaner API.

### Solution
- Move the navigateXX function into the FwPosController. They are responsible to convert the setpoint triplets into a path setpoint.
- Update the npfg to only rely on one single navigatePath input function, which is used to navigate to the desired path.

### Test coverage
- Tested in SImulation using the standard_vtol gazebo simulation.

### Context
Related links, screenshot before/after, video

2023-02-06 18:15 UTC, tstastny requested changes
Thanks for getting this rolling @KonradRudin !

@dagar just heads up - this is first steps in a larger fixed-wing control refactor. end game is split up "path controller" "course controller" and "heading controller". no exotic setpoints, just standard vehicle states.

2023-02-06 18:15 UTC, tstastny commented on src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
> +	    && close_to_circle && _param_fw_lnd_earlycfg.get()) {
maybe while we're at it, could also move
```cpp
} else {
	_att_sp.apply_flaps = vehicle_attitude_setpoint_s::FLAPS_OFF;
	_att_sp.apply_spoilers = vehicle_attitude_setpoint_s::SPOILERS_OFF;
}
```
out of the else condition and just set it in the same place as the original `airspeed_sp` initialization. Then it just gets overwritten by the if condition. slightly less messy? (also makes it easier later to see that we anyway need to extract this landing logic out of this orbit method)

2023-02-06 21:55 UTC, sfuhrer commented on src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
> +	    && close_to_circle && _param_fw_lnd_earlycfg.get()) {
Or we get https://github.com/PX4/PX4-Autopilot/pull/20815 in finally and not have to anymore deal with flaps/spoiler setpoints in the attitude setpoint?

2023-02-07 14:11 UTC, KonradRudin commented on src/modules/fw_pos_control_l1/FixedwingPositionControl.cpp
> +	    && close_to_circle && _param_fw_lnd_earlycfg.get()) {
@sfuhrer even with your PR, the logic to set them should still be the same, it only sets them in another uorb topic, right? So i can still change the proposed changes from tstastny?

2023-02-07 15:18 UTC, tstastny submitted a review, later dismissed
Still some checks failing - but otherwise gtg from my side.

2023-02-08 06:48 UTC, KonradRudin commented
@tstastny can you approve again? I just did a rebase on newest master and cleanup of the commits. The clang tidy error was a bug, rerunning it fixed it. The other errors are flash errors which are already present in main.

2023-02-08 07:21 UTC, tstastny approved these changes

2023-02-08 07:54 UTC, merged