drivers/imu/bosch/bmi088: add more time between configure and FIFO_READ
PX4/PX4-Autopilot pull request #21111
Opened 2023-02-10 16:15 UTC by dagar

- new FIFO_RESET state used to give the sensor more time after successful configuration before sampling begins

2023-02-10 16:49 UTC, bresch requested changes

2023-02-10 16:49 UTC, bresch commented on src/drivers/imu/bosch/bmi088/BMI088_Accelerometer.cpp
> +			ScheduleDelayed(1_ms);
```suggestion
			ScheduleDelayed(10_ms);
```

2023-02-10 21:24 UTC, bresch approved these changes

2023-02-11 02:38 UTC, dagar commented on src/drivers/imu/bosch/bmi088/BMI088_Gyroscope.cpp
> +			ScheduleDelayed(1_ms);
```suggestion
			ScheduleDelayed(10_ms);
```

Might as well keep gyro and accel in sync.

2023-02-14 02:01 UTC, merged