systemcmds/mtd: fix rwtest - force data to/from the device
PX4/PX4-Autopilot pull request #21180
Opened 2023-02-22 08:52 UTC by Igor-Misic

This is a fix for systemcmds/mtd **rwtest** where the test was not actually testing the physical device. 

I was debugging the Block device with **rwtest** when I notice that it execute a little bit too fast (thanks to @bkueng noticing this on EEPROM tests).

Block Device has its own buffer and logic to not write to the device unless it needs to change sector. 
So in the case where the FRAM sector size is 512 bytes and we are writing 128-byte chunks, it will use its buffer to write 4x chunks of 128 bytes before it will physically write data over SPI. This means the read command that is going after write will use data from the 512-byte size buffer.

I've decided to use this KISS method by doing `fsync` and `close(fd)` after writing. This way 128-byte chunk will be physically written and the buffer will be dropped. 

I was thinking also about the solution of variable size of test buffer but it could be an issue for the stack if the device has huge sectors. Also, another solution to use some other test algorithm to change sector size to force read/write would make things more complicated.

2023-02-22 11:18 UTC, davids5 requested changes
@Igor-Misic Good catch!

Since it is a test On close() & fsync() we should check returns

2023-02-23 07:27 UTC, bkueng commented on src/systemcmds/mtd/mtd.cpp
>  				return 1;
These returns are missing a `close(fd);`

2023-02-23 07:27 UTC, bkueng commented on src/systemcmds/mtd/mtd.cpp
> +			if (count == expected_size) {
```suggestion
			if (count >= expected_size) {
```

2023-02-24 07:08 UTC, bkueng approved these changes

2023-02-24 07:08 UTC, merged