Gazebo simulation: Used Gazebo GPS plugin
PX4/PX4-Autopilot pull request #21187
Opened 2023-02-23 17:31 UTC by ahcorde

Added Gps sensor that allows to setup the GPS in Gazebo

I'm getting these errors. Any thoughts?

```
WARN  [health_and_arming_checks] Preflight Fail: Strong magnetic interference
WARN  [health_and_arming_checks] Preflight Fail: Yaw estimate error
```

FYI @Jaeyoung-Lim @bperseghetti @dagar

2023-02-23 17:34 UTC, Jaeyoung-Lim commented on Tools/simulation/gz/models/x500/model.sdf
> +      </sensor>
Are you actually using the mangnetometer? I don't see this being consumed anywhere

2023-02-23 17:41 UTC, Jaeyoung-Lim requested changes
@ahcorde Thanks for already looking into these!

Are the mag issues present when just adding the GPS sensor?

If this is the case, wondering if it is related to the WMM magnetic model? 

https://github.com/PX4/PX4-Autopilot/blob/a1efafc42bb53d09f44236efebab168b33fbcd2b/src/modules/ekf2/ekf2_params.c#L1468-L1480

2023-02-23 17:41 UTC, Jaeyoung-Lim commented on src/modules/simulation/gz_bridge/GZBridge.hpp
> +	void navsatCallback(const gz::msgs::NavSat &_msg);
```suggestion
	void gpsCallback(const gz::msgs::NavSat &_msg);
```

2023-02-23 17:41 UTC, Jaeyoung-Lim commented on src/modules/simulation/gz_bridge/GZBridge.cpp
> +	sensor_gps.cog_rad = atan2(navsat.velocity_north(),
Downward should be positive?

2023-02-23 17:41 UTC, Jaeyoung-Lim commented on src/modules/simulation/gz_bridge/GZBridge.cpp
> +	sensor_gps.vel_e_m_s = navsat.velocity_north();
Was it intentional that the north is converted to east?

2023-02-23 17:44 UTC, Jaeyoung-Lim commented on ROMFS/px4fmu_common/init.d-posix/airframes/4001_gz_x500
> +param set-default SENS_EN_GPSSIM 0
Since the default is zero, we can actually remove this line completely

2023-02-23 17:52 UTC, ahcorde commented
> @ahcorde Thanks for already looking into these!
> 
> Are the mag issues present when just adding the GPS sensor? If this is the case, wondering if it is related to the WMM magnetic model or something related to the geolocation and mag consistency
> 
> https://github.com/PX4/PX4-Autopilot/blob/a1efafc42bb53d09f44236efebab168b33fbcd2b/src/modules/ekf2/ekf2_params.c#L1468-L1480

I was trying to include both at the same time (gps and magnetometer) but it's not clear for me how to match the values:

The magnetometer from Gazebo has magnetic field strength (in Tesla) along body-frame axis. I checked the `PX4Magnetometer` class but I couldn't find documentation.

2023-02-23 17:56 UTC, Jaeyoung-Lim commented
> I was trying to include both at the same time (gps and magnetometer) but it's not clear for me how to match the values:

Does this mean that in gazebo, when there is a spherical coordinate defined as geo coordinates, the magnetic field is not consistent with the geolocation of the world?

2023-02-24 12:46 UTC, ahcorde commented
> > I was trying to include both at the same time (gps and magnetometer) but it's not clear for me how to match the values:
> 
> Does this mean that in gazebo, when there is a spherical coordinate defined as geo coordinates, the magnetic field is not consistent with the geolocation of the world? If this is the case, would it be something desired to add this feature?
> 
> This was how it was being done for gazebo classic: https://github.com/PX4/PX4-SITL_gazebo-classic/blob/ec8641d48753b20d431842f88e95557f22ec318a/src/gazebo_magnetometer_plugin.cpp#L184-L197

Yep, this feature was not implemented in Gazebo, but here it is https://github.com/gazebosim/gz-sim/pull/1907. 

I still have some issue with the NED -> ENU conversion. The velocity published in the navsat msg is in ENU, but the internal px4 message is in NED coordinates. may this affect the magnetometer too ?

2023-02-26 12:24 UTC, Jaeyoung-Lim commented
> I still have some issue with the NED -> ENU conversion. The velocity published in the navsat msg is in ENU, but the internal px4 message is in NED coordinates. may this affect the magnetometer too ?

I would doubt that this makes a difference unless it happens during motion. Could you try disabling `EKF2_MAG_CHECK` and see if it fixes the problem before the mag PR is merged?

2023-02-26 12:26 UTC, Jaeyoung-Lim commented on Tools/simulation/gz/worlds/default.sdf
> +      <elevation>0</elevation>
Just retaining legacy behavior :) 
```suggestion
      <latitude_deg>47.397742</latitude_deg>
      <longitude_deg>8.545594</longitude_deg>
      <elevation>488.0</elevation>
```

2023-02-27 12:47 UTC, ahcorde commented
> `EKF2_MAG_CHECK`

I added this param but I still have the issue

![quad_copter_fail_gps](https://user-images.githubusercontent.com/1933907/221567191-3ca69513-fd95-49e5-8721-8db5eb5f3385.gif)

2023-02-27 12:50 UTC, Jaeyoung-Lim commented
> EKF2_MAG_CHECK
I added this param but I still have the issue

@bresch @dagar Any ideas how to fix this?

2023-03-01 15:13 UTC, bresch commented
I tried in sim to fake a large mag field and I can arm without issues in alt mode if EKF2_MAG_CHECK is set to 0 or if COM_ARM_MAG_STR is set to 0.

2026-04-24 08:10 UTC, closed without merging