Add USB to Serial Config for MicroDDS
PX4/PX4-Autopilot pull request #21233
Opened 2023-03-02 00:07 UTC by AlexKlimaj

This PR adds USB to the serial port configurations in order to use USB for microdds.

```
Starting Micro XRCE-DDS on /dev/ttyACM0
INFO  [microdds_client] synchronized with time offset 1677715250584074us
INFO  [microdds_client] successfully created rt/fmu/out/failsafe_flags data writer, topic id: 84
INFO  [microdds_client] successfully created rt/fmu/out/sensor_combined data writer, topic id: 170
INFO  [microdds_client] successfully created rt/fmu/out/timesync_status data writer, topic id: 190
INFO  [microdds_client] successfully created rt/fmu/out/vehicle_attitude data writer, topic id: 207
INFO  [microdds_client] successfully created rt/fmu/out/vehicle_control_mode data writer, topic id: 213
INFO  [microdds_client] successfully created rt/fmu/out/vehicle_local_position data writer, topic id: 220
INFO  [microdds_client] successfully created rt/fmu/out/vehicle_odometry data writer, topic id: 225
INFO  [microdds_client] successfully created rt/fmu/out/vehicle_status data writer, topic id: 230

nsh>
nsh>
nsh> microdds_client status
INFO  [microdds_client] Running, connected
INFO  [microdds_client] Payload tx: 49970 B/s
INFO  [microdds_client] Payload rx: 0 B/s
nsh>
```

On the Jetson
![image](https://user-images.githubusercontent.com/2019539/222295524-a8d75824-efe9-4bfe-a410-91108e4ba1af.png)

2023-03-02 01:41 UTC, beniaminopozzan commented
Thanks @AlexKlimaj !
Is it possible to extend it to other boards?

2023-03-02 01:47 UTC, AlexKlimaj commented
> Thanks @AlexKlimaj ! Is it possible to extend it to other boards?

Yeah, I don't see why not.

2023-03-02 02:11 UTC, dagar commented
I think this is the right direction, but needs to be coordinated with the existing autostart stuff.

2023-03-02 04:42 UTC, AlexKlimaj commented
It appears to play nice with the mavlink usb auto start.

2023-03-06 14:39 UTC, dagar requested changes
I believe to do this properly we need to slip in `sercon` somewhere to start NuttX CDCACM, and then in the autostart code have it skip if sercon already start or /dev/ttyACM0 exists. https://github.com/PX4/PX4-Autopilot/blob/e5d5fcd3153602907d4a94ee50b68dd99c76e138/platforms/nuttx/src/px4/common/cdc_acm_check.cpp#L117-L122

It's also critical that we don't perform the disconnect cleanup because most of these apps will not fail gracefully if /dev/ttyACM0 disappears.

https://github.com/PX4/PX4-Autopilot/blob/e5d5fcd3153602907d4a94ee50b68dd99c76e138/platforms/nuttx/src/px4/common/cdc_acm_check.cpp#L355-L359

2023-12-14 07:25 UTC, junwoo091400 commented
Maybe dumb question, but we can't connect the QGC or HITL interface through the USB port when the DDS is in use right?

I ended up in a situation where I can't connect to the FC anymore because the DDS is running :laughing:. Did you run into this problem too? If so, how did you access the FC to change the config (e.g. disable DDS on USB) @AlexKlimaj ?

2024-04-20 13:43 UTC, carbide2004 commented
I tried this method, but it still didn't work. I use CUAV x7 pro with px4 firmware, set UXRCE_DDS_CFG "TELEM1", and have disabled MAVLink. The baud rate "SER_TEL1_BAUD" is set the same as the value after "-b". I also start Micro XRCE-DDS on /dev/ttyACM0. I'm wondering what happened.

2026-08-12 02:15 UTC, closed without merging