remove settings.json from repo to prevent conflicts
PX4/PX4-Autopilot pull request #21333
Opened 2023-03-18 09:49 UTC by christianrauch

### Solved Problem

I always have to reset the `.vscode/settings.json` when switching branches, due to vscode adding new changes automatically to this file. This goes along with similar issues reported with https://github.com/PX4/PX4-Autopilot/pull/21063.

### Solution
Remove the file `.vscode/settings.json` entirely to prevent conflicts and let users choose their own settings.

Temporary files, such as user settings, should not be committed to a version control system.

### Alternatives
Use a different IDE.

2023-03-21 01:49 UTC, dagar requested changes
Sorry, but we need this for a decent out of the box experience. 

What conflicts are you seeing? In my experience most of them can be resolved and it greatly benefits everyone.

2023-03-21 01:53 UTC, dagar commented
> Remove the file .vscode/settings.json entirely to prevent conflicts and let users choose their own settings.

It's not about "users choose their own settings" it's about being able to clone and having things like build and debug working without manual setup.

2023-03-21 22:31 UTC, christianrauch commented
> What conflicts are you seeing?

It's basically happening when vscode adds content to that file, e.g. because of another extension. It's not a merge conflict. It's simply git refusing to switch branches because of uncommitted changes.

If this happens, you have to close vscode, reset the file manually via git and just then can you switch branches. This is very annoying and far away from a good out-of-the-box experience. As soon as you open vscode again, the file will have changes and you have to repeat the steps to switch branches.

> In my experience most of them can be resolved and it greatly benefits everyone.

Wouldn't it be better to make this optional, e.g. by providing the file in a "config" folder and instructions on how to set up vscode or another editor/IDE with such a config file? Because then it would also work for users where the PX4 selected settings conflict with the user's own choice.

2023-03-22 01:53 UTC, dagar commented
If we absolutely can't find a solution then perhaps moving to settings.json.default or something could work, but it's just not ideal. The whole point is to share these settings.

2023-03-22 02:00 UTC, dagar commented
For example vscode itself has its workspace .vscode/settings.json committed. https://github.com/microsoft/vscode/blob/main/.vscode/settings.json

Isn't this the entire point of having separate workspace (aka project) settings and individual user settings?

2023-03-22 22:25 UTC, christianrauch commented
> Isn't this the entire point of having separate workspace (aka project) settings and individual user settings?

But this does not seem to work in vscode, e.g. see the discussion about the [right-click behaviour](https://github.com/PX4/PX4-Autopilot/pull/21063#issuecomment-1419571166). This has been resolved since, but it demonstrates how the workspace settings deviate from the default setting of getting a context menu on right click.

On top of this, because vscode may automatically add changes to the settings file in the workspace, you constantly have to deal with these uncommitted changes in git. Therefore this PR.

> For example vscode itself has its workspace .vscode/settings.json committed.

This may all come down to personal preference, but I rarely see git repos with the IDE-specific configs committed. I would even say that less than 5% of git repos on GitHub have IDE-specific files committed. E.g. https://github.com/mavlink/qgroundcontrol also does not have vscode or similar settings (e.g. a `CMakeLists.txt.user` created by Qt Creator) in the repo.

2023-03-23 00:45 UTC, dagar commented
> But this does not seem to work in vscode, e.g. see the discussion about the https://github.com/PX4/PX4-Autopilot/pull/21063#issuecomment-1419571166. This has been resolved since, but it demonstrates how the workspace settings deviate from the default setting of getting a context menu on right click.

I'm not sure what you mean, the user configuration takes precedence over the workspace. 

> On top of this, because vscode may automatically add changes to the settings file in the workspace, you constantly have to deal with these uncommitted changes in git.

Any specific examples? It might be something that can be silenced/fixed. FYI you don't have to close vscode to checkout or reset the file.

As I said I'm happy to remove any opinionated preferences that slipped into the workspace settings and help work through any problems, but let's not give up on this mechanism out of some sense of purity. Being able to clone and have most things "just work" is important for a project like this where there's a lot of inexperienced developers (students and engineers that aren't necessarily software developers).

2023-03-23 22:04 UTC, christianrauch commented
> Any specific examples? It might be something that can be silenced/fixed.

Specifically, it is the extension `ms-iot.vscode-ros`, which is recommended here: https://github.com/PX4/PX4-Autopilot/blob/5b6d1e9290e335fd9cdc1175fa875ea149ac1b79/.vscode/extensions.json#L11

This extension causes the diff:
```diff
diff --git a/.vscode/settings.json b/.vscode/settings.json
index 1bf4e6eb2f..67c2661ca9 100644
--- a/.vscode/settings.json
+++ b/.vscode/settings.json
@@ -136,5 +136,10 @@
         "yaml.schemas": {
                 "${workspaceFolder}/validation/module_schema.yaml": "${workspaceFolder}/src/modules/*/module.yaml"
         },
-        "cortex-debug.openocdPath": "${env:PICO_SDK_PATH}/../openocd/src/openocd"       // Added for rp2040
+        "cortex-debug.openocdPath": "${env:PICO_SDK_PATH}/../openocd/src/openocd",
+        "ros.distro": "humble",
+        "python.autoComplete.extraPaths": [
+                "/opt/ros/humble/lib/python3.10/site-packages",
+                "/opt/ros/humble/local/lib/python3.10/dist-packages"
+        ] // Added for rp2040
 }
```

> FYI you don't have to close vscode to checkout or reset the file.

As soon as you do:
```sh
git checkout .vscode/settings.json
```
in the vscode shell, the change (see above) will be applied gain since vscode is running in parallel.

As a counter-example, you can close vscode, checkout the file and see that it is not listed under changed files anymore. But as soon as you load the project with vscode again and have the extension enabled, the change will be applied, preventing you from changing branches.

> Being able to clone and have most things "just work" is important for a project like this where there's a lot of inexperienced developers (students and engineers that aren't necessarily software developers).

IMHO, suggesting an extension that automatically applies changes to a file that is tracked via git is the opposite of "just works". I am sure that people can follow instructions on how to compile PX4 but they will have a harder time figuring out why they cannot switch git branches.

2025-01-28 15:19 UTC, closed without merging