change offboard control mode check order
PX4/PX4-Autopilot pull request #21454
Opened 2023-04-10 13:08 UTC by damien-robotsix

### Solved Problem
From control_mode.cpp, only one offboard mode is allowed at a time. However, nothing prevent to raise several flag at the same type. 
As, for example in mavlink receiver
https://github.com/PX4/PX4-Autopilot/blob/0cfe1350281579ef3d009944cc8810850a2604d9/src/modules/mavlink/mavlink_receiver.cpp#L1530-L1599

As a consequence, if several flags are raised together, the commander will select only one of them. Which is fine, apart from the fact the some flags enable more control loop than others. 

As it is done now, when a set attitude target is received from Mavlink with the default typemask, it leads to both the offboard_control_mode.attitude and offboard_control_mode.body_rate to be raised.

Then both the attitude controller and rate controller are allowed to run while the Mavlink receiver publishes on vehicle_rate_setpoint and vehicle_attitude_setpoint.
As the attitude controller also publish on vehicle_rate_setpoint. Leading to undefined behavior as two sources publish on the vehicle_rate_setpoint.

I propose to change the order of the check in the commander to choose the most restrictive case when several offboard_control_mode flags are raised.

An other solution would be to handle better malformed typemask in the Mavlink receiver but it will not avoid a similar issue from other sources.

2023-04-10 14:20 UTC, Jaeyoung-Lim requested changes
This would break the usage of having a higher level reference use a lower level as reference.

For example, if position and velocity are both enabled we want to run the position controller and use the additional velocity reference as a feedforward.

However, this PR would make the controller to ignore position references all together

2023-04-10 14:33 UTC, PetitPrince6 commented
I don't agree. If you are in position controller, you can still use velocity as feedforward even like this. Today, those flags are treated as if they were exclusive anyway. If you want to use position with feedforward, you just raise the position flag. The modification only affects how multiple flag raised are resolved. It shouldn't happen but if it happens, I would prefer to select the most restrictive case.

2023-04-10 16:13 UTC, Jaeyoung-Lim commented
>  Today, those flags are treated as if they were exclusive anyway. 

I don't think this is true. Both mc_pos_control and fw_pos_control supports mixing flags with pos, vel, acc setpoints.

>  If you want to use position with feedforward, you just raise the position flag.

IMHO, this would lead to a more confusing interface, where with the same mode flag you can have different behaviors depending on the velocity and acceleration values. What makes it even more confusing is that if the user does not populate the `trajectory_setpoint.msg`, the default value would be zero meaning that it will try to use the unpopulated fields even if only the position flags have been raised.

2023-04-17 04:26 UTC, Jaeyoung-Lim commented
>  Avoiding a malformed message to raise the offboard_control_mode.attitude AND publish on vehicle_rate_setpoint at the same time? But then what is a different vehicle type needs it as FFW some day?

Exactly, so in principle, this is not a malformed message. It is the cascaded implementation in PX4 that is problematic. IMHO, for offboard mode the user is fully responsible for sending a correct message. The whole point of offboard mode is to remove all the braces and safety harnesses so that development is easier.

2023-04-17 07:27 UTC, closed without merging

2023-04-17 07:32 UTC, Jaeyoung-Lim commented
@PetitPrince6 Oh, I am sorry to hear that. Maybe

Unfortunately I cant find the discord thread anymore. Would you be able to link it here?  I am missing some context here.

2023-04-17 07:40 UTC, damien-robotsix commented
https://discord.com/channels/1022170275984457759/1022185868317966458/1080847841888583802