[mavlink_messages] Missmatch between header macros and class used
PX4/PX4-Autopilot pull request #21603
Opened 2023-05-17 14:07 UTC by loicdubois

### Solved Problem
Trying to get the SYSTEM_TIME mavlink stream to work 
```
WARN  [mavlink] stream SYSTEM_TIME not found
ERROR [mavlink] configure_streams_to_default() failed
```
Fixes #{Github issue ID}

### Solution
Simply add the stream corresponding to the right header preprocessor directives

### Changelog Entry
Bugfix: SYSTEM_TIME stream not found

### Alternatives
-

### Test coverage
- add stream to desired mode
- SITL starts without complaining

### Context
-

2023-05-17 16:25 UTC, junwoo091400 commented
Sorry, accidentally closed it!

2023-05-17 18:09 UTC, dagar commented
Good catch @loicdubois, perhaps we should just generate this instead.

2023-05-19 14:50 UTC, dagar commented on src/modules/mavlink/mavlink_messages.cpp
> +#if defined(SYSTEM_TIME_HPP)
SYSTEM_TIME is now being added twice (see below ~ line 379).

2023-05-19 14:51 UTC, dagar requested changes
Fixing SYS_STATUS is correct, but SYSTEM_TIME doesn't need to be added.

2023-05-22 14:10 UTC, loicdubois commented
> What is the use case for this? Could you give some context?

I actually don't use it, just got a warning by playing around with streams to add and remove

2023-05-24 00:41 UTC, dagar approved these changes

2023-05-24 00:44 UTC, merged