SITL: fix gazebo garden carsh in VMware virtual machine
PX4/PX4-Autopilot pull request #21617
Opened 2023-05-20 02:58 UTC by TianmingLi

### Solved Problem

Fixes #21607

### Solution
- Force gazebo use render engine `ogre` rather than `ogre2` 

### Changelog Entry

### Alternatives

### Test coverage

### Context

2023-05-22 13:13 UTC, Jaeyoung-Lim reviewed
This probably needs more testing on other systems.

Why does this make a difference for a virtual machine, and what are the implications of using ogre2 vs ogre?

2023-05-22 13:16 UTC, Jaeyoung-Lim requested changes
From the discussion in https://github.com/conda-forge/libignition-gazebo-feedstock/issues/27, it looks like we cannot use ogre1 with ROS2

2023-06-05 20:05 UTC, MaEtUgR commented
Thanks @TianmingLi, this also fixes the UI in WSL! For the first time I get to even test one of these gz targets without it crashing immediately 😲
![image](https://github.com/PX4/PX4-Autopilot/assets/4668506/2efd5b2a-1afd-4a7f-9363-7e0f5ab7a5de)
FYI @hamishwillee that's what we were looking for.

Maybe we can automatically add this option for VMWare and WSL similar to https://github.com/PX4/PX4-Autopilot/blob/c468266b27273d597c0d67b794400384e6eeab1e/Tools/setup/ubuntu.sh#L267-L270 🤔

2023-06-10 01:25 UTC, dagar commented
Here's a workaround. https://github.com/PX4/PX4-Autopilot/pull/21712

2025-01-03 13:56 UTC, FarziBuilder commented
This worked for me at the system Ubuntu 20.04, gazebo-garden version

2026-08-10 02:17 UTC, closed without merging