[WIP] STM32H7 Can Filter & Can bus-off State Handling
PX4/PX4-Autopilot pull request #21701
Opened 2023-06-08 09:30 UTC by henrykotze

Exception handling for bus-off state in the STM32H7 driver, and first go at implementing the CAN filters

Based on the following STM32 Documents:
RM0433 - Reference manual for STM32H742, STM32H743/753 and STM32H750 Value line
AN5348 - Introduction to FDCAN peripherals for STM32 product classes
TN1367 - Bus off management in MCAN controllers

# Context
* Our ESCs on powerup, causes the CAN bus to go into bus-off state. Currently their is no handling of this state in the STM32H7 driver, and results in the FMU to be 'kicked' off from the Canbus.

# Implementation
* Added the can bus off state into the interrupt register, and handling this state.  Currently in both interrupts, there is a check for whether this interrupt has been triggered, but it might only be necessary on one of them. 
* Added Can filters, unsure whether they work as intended (I dont think they do), would be great if someone with more experience have a look at this.

2023-06-08 10:55 UTC, davids5 requested changes
See inline

2023-06-08 10:55 UTC, davids5 commented on src/drivers/uavcan/uavcan_drivers/stm32h7/driver/src/uc_stm32h7_can.cpp
> +	} else if ((fdcan::Can[iface_index]->IR & FDCAN_IR_BO) > 0) {
```suggestion
	} else if ((fdcan::Can[iface_index]->IR & FDCAN_IR_BO) != 0) {
```
Mixing bit ops and magnitude testing is a bit odd.

2023-06-08 10:55 UTC, davids5 commented on src/drivers/uavcan/uavcan_drivers/stm32h7/driver/src/uc_stm32h7_can.cpp
> +	} else if ((IR & FDCAN_IR_BO) > 0) {
Ditto

2023-06-08 10:55 UTC, davids5 commented on src/drivers/uavcan/uavcan_drivers/stm32h7/driver/src/uc_stm32h7_can.cpp
> +					// uint32_t id = 0;
Remove commented out code or place in an #if if it is a option

2023-06-08 10:55 UTC, davids5 commented on src/drivers/uavcan/uavcan_drivers/stm32h7/driver/src/uc_stm32h7_can.cpp
> +
Can this be removed?

2023-06-08 16:15 UTC, henrykotze commented
# Standard Filter Register
![image](https://github.com/PX4/PX4-Autopilot/assets/24815968/750475a6-214f-4a89-8a1b-6d21a44f6cd2)
![image](https://github.com/PX4/PX4-Autopilot/assets/24815968/e23641f5-e5ee-4701-af98-c0c04f8e90a6)

# Extended Filter Register
![image](https://github.com/PX4/PX4-Autopilot/assets/24815968/3d45d63f-50b0-4ec1-806e-38033db5b279)
![image](https://github.com/PX4/PX4-Autopilot/assets/24815968/335dcf48-466b-4b8c-bc14-64766d1ce6c5)

Would be great if someone could have a peek if the way how I implement the filter are correct, because I am not too sure if they are working as intended.

2023-06-30 19:18 UTC, henrykotze commented
@davids5 anything else here to do, except for squash comments?

I can confirm the bus is much more stable. We can short the CANH and CANL, and it will recover perfectly. The only thing I am unsure about is the filter implementation. @JacobCrabill do you have comments or suggestion to make? I just @ you due to your work on the initial driver work :)

2023-07-03 11:38 UTC, davids5 requested changes
@henrykotze LGTM but please squash/Fix it up the commits

2023-07-03 12:18 UTC, davids5 approved these changes

2023-07-12 15:56 UTC, merged