ubuntu.sh: updated dependencies and output
PX4/PX4-Autopilot pull request #21808
Opened 2023-07-05 19:59 UTC by mrpollo

OK Let's try this again (#19905)

The ubuntu.sh install script was starting to carry some outdated dependencies and was confusing for newcomers trying to set up a development environment. I double-checked each dependency and made sure to build each PX4 target
including FastRTPS and Simulations with the new install script

Here's a breakdown of what I did:

* removed unused dependencies
* Removed JAVA / JMAVSim
* Added conditional support for use in a container environment via a new flag --from-docker
* Added multi-platform build tools for development
* Cleaned up Gazebo installation

2023-07-05 21:40 UTC, mrpollo commented
Hey @dagar I added a simple test for ubuntu 20/22 that runs the script, at least we will know if there's anything broken, next step we should try to build a few targets with this environment

2023-07-07 18:20 UTC, beniaminopozzan requested changes
@mrpollo , I focused on the simulation part.
As I didn't see any change in the dependencies for the simulation infrastructure, I would suggest to keep the installation script as it is and just remove Java.
If instead we want to perform this refactoring, then I left a few comments. The most critical one is that gazebo is not installed on Ubuntu 22 and that Gazebo Garden (instead of classic) is installed on Ubuntu 20.

Side note: if the dependencies for jmavsim are removed, the documentation has to be updated.

2023-07-07 18:20 UTC, beniaminopozzan commented on Tools/setup/ubuntu.sh
> +fi
The installation of `gstreamer` and the other packages is already done in `install_gazebo_common`

2023-07-07 18:20 UTC, beniaminopozzan commented on Tools/setup/ubuntu.sh
> +	install_gazebo_common
`install_gazebo_common` is called twice. The first one is after `if [[ $INSTALL_SIM == "true" ]]; then`

2023-10-20 09:42 UTC, julianoes commented
I'd side with @Pedro-Roque. It would be good to have the option for Gazebo Classic.

2024-08-16 17:22 UTC, closed without merging

2024-08-21 04:44 UTC, hamishwillee commented
FWIW I don't know why we can't have sim-specific options. In any case, the [documentation for ubuntu setup](https://docs.px4.io/main/en/dev_setup/dev_env_linux_ubuntu.html) now has this comment

<img width="597" alt="image" src="https://github.com/user-attachments/assets/0a7eb967-7a31-4359-b0bd-ce9b8fecd4ed">