EKF2: use timestamp from argument of PublishEvPosBias()
PX4/PX4-Autopilot pull request #21822
Opened 2023-07-08 19:41 UTC by sfuhrer

### Solved Problem
The timestamps of estimator_ev_pos_bias are broken in EKF replay.

### Solution
Fill timestamp field with what was passed into PublishEvPosBias() as an argument instead of calling hrt_absolute_time().

2023-07-08 19:44 UTC, bresch requested changes

2023-07-08 19:44 UTC, bresch commented on src/modules/ekf2/EKF2.cpp
> +			bias.timestamp = timestamp;
```suggestion
			bias.timestamp = _replay_mode ? timestamp : hrt_absolute_time();
```

2023-07-08 19:49 UTC, sfuhrer commented on src/modules/ekf2/EKF2.cpp
> +			bias.timestamp = timestamp;
:bulb:

2023-07-11 09:07 UTC, bresch approved these changes

2023-07-11 09:07 UTC, merged