Fix CI for deprecated set-output
PX4/PX4-Autopilot pull request #21848
Opened 2023-07-13 09:37 UTC by farhangnaderi

### Solved Problem
The 'set-output' function is deprecated and needs to be replaced. As @mrpollo mentioned I tried to make the changes. 

### Solution
- Replace the deprecated 'set-output' function with the recommended alternative 'echo ::set-output'.

### Changelog Entry
For release notes:

"Replaced deprecated 'set-output' function with 'echo ::set-output' in Ci "

### Alternatives
We could also continue using the deprecated 'set-output' function, but it's recommended to use the new syntax.

### Test coverage
- Unit/integration test: N/A (No changes impacting tests)
- Simulation/hardware testing logs: N/A

### Context
N/A (No specific context or related links for this PR)

2023-07-19 14:49 UTC, mrpollo requested changes
@farhangnaderi can you please rollback the whitespace fixes? let's keep this PR exclusive to the set-output change

2023-07-19 14:49 UTC, mrpollo commented on .github/workflows/cflite_batch.yml
> +   # - cron: '0 6 * * *'  # UTC 6am every day.
do you mind cleaning up? plz uncomment

2023-07-19 14:49 UTC, mrpollo commented on .github/workflows/compile_macos.yml
> -    runs-on: macos-10.15
this is conflicting with a recent PR that came in

2023-07-19 18:15 UTC, farhangnaderi commented
> @farhangnaderi can you please rollback the whitespace fixes? let's keep this PR exclusive to the set-output change

@mrpollo you may check, pushed a new one, let me know if I am still lost somewhere! :)

2023-07-26 15:24 UTC, junwoo091400 commented
@farhangnaderi could you remove the whitespace changes?

2023-07-26 15:25 UTC, dagar commented on .github/workflows/deploy_all.yml
> -        AWS_S3_BUCKET: 'px4-travis'
Is this change intentional?

2023-07-26 21:41 UTC, farhangnaderi commented on .github/workflows/deploy_all.yml
> -        AWS_S3_BUCKET: 'px4-travis'
no, me missing it. Corrected I guess!

2023-07-26 21:42 UTC, farhangnaderi commented
> @farhangnaderi could you remove the whitespace changes?

did not again? missed some! my bad! must be ok now!

2024-12-12 23:22 UTC, closed without merging