Update quaternion covariance at yaw reset
PX4/PX4-Autopilot pull request #22023
Opened 2023-08-30 17:34 UTC by Donecle

### Solved Problem
When looking in detail at quaternion states variances in the logs, I noticed that on similar missions, values are not the same depending on the initial yaw.
The problem is that quaternion variances depend on the quternion itself. So if there is a reset in yaw, which changes the quaternion states, quaternion covariance matrix also needs to be updated, which is not the case for now.

### Solution
When doing a yaw reset, save the quaternion covariances as Euler angles so that they can be restored after the reset.

2023-08-30 17:46 UTC, Donecle commented
Oops, looks like the 'initialiseQuatCovariances' function does not exist anymore... Should I do another pull request with this function back from the dead ?

2023-09-05 07:09 UTC, Donecle commented
Ok, thanks for the inputs. I'll try to make the changes, probably this week.

2023-09-05 12:53 UTC, Donecle commented
I can see that the initialization of EKF at 90 degrees test is not passing, I'm interested if you find why. It could be related to a fusion failure we have sometimes in flight, which is the reason why I was looking into this code first.

2023-09-13 12:12 UTC, bresch requested changes
You need to pre- and post- multiply a covariance matrix to rotate it.
Otherwise looks good!

2023-09-13 12:12 UTC, bresch commented on src/modules/ekf2/EKF/ekf_helper.cpp
> +	Vector3f rot_vec_var_before_reset = _R_to_earth * calcRotVecVariances();
```suggestion
	Vector3f rot_vec_var_before_reset = _R_to_earth * calcRotVecVariances() * _R_to_earth.T();
```

2023-09-22 12:05 UTC, bresch commented
I rebased the PR and fixed the implementation. Could you please check if that works for you now? https://github.com/PX4/PX4-Autopilot/pull/22123

2023-09-22 12:05 UTC, closed without merging