Change INA238_SHUNT Default Value for Consistency
PX4/PX4-Autopilot pull request #22051
Opened 2023-09-07 08:09 UTC by vincentpoont2

### Solved Problem
Change INA238_SHUNT Default Value from 0.0003 to 0.0005 for Consistency with INA226 & INA228.

[INA226 ](https://github.com/PX4/PX4-Autopilot/blob/35c1d5d9b1f80bb964f33a6686774d8a85415f77/src/drivers/power_monitor/ina226/ina226_params.c#L76)& [INA228](https://github.com/PX4/PX4-Autopilot/blob/35c1d5d9b1f80bb964f33a6686774d8a85415f77/src/drivers/power_monitor/ina228/ina228_params.c#L76) both has value 0.0005 (500μOhm Shunt), but INA238 had value of 0.0003 (300μOhm Shunt). 

Using 300μOhm Shunt over 500μOhm would lose some current reading accuracy and benefit is minimal, so consistency across the board should prioritized, giving end user a better experience. 

### Context
At the moment, there doesn't seems to be any other Digital power module that uses INA238 other than Holybro. 

### To Do
Once merge, the [INA238_SHUNT default on PX4 doc ](https://docs.px4.io/main/en/advanced_config/parameter_reference.html)should change accordingly.

2023-09-07 13:54 UTC, dagar commented
We need to be careful this doesn't break any existing usage.

2023-09-07 14:39 UTC, vincentpoont2 commented
> We need to be careful this doesn't break any existing usage.

@dagar  As in existing products that uses INA238?

2023-09-07 14:49 UTC, dagar commented
> > We need to be careful this doesn't break any existing usage.
> 
> @dagar As in existing products that uses INA238?

I believe so, that's why the driver exists. :smirk:

2023-09-07 14:59 UTC, ThomasDebrunner commented
We have a power module with INA238 that has a 0.0003 shunt resistor, hence the initial value for this when writing the driver

2023-10-19 21:39 UTC, julianoes commented
Now that we have https://github.com/PX4/PX4-Autopilot/pull/22073, could we change the default to what @vincentpoont2 suggests?

2023-12-12 17:14 UTC, niklaut commented
Yes, I think this would be backward compatible for us if we added these lines to our power monitor:

```cpp
	static constexpr int SENSORS_NUMBER{6};

	Sensor _sensors[SENSORS_NUMBER] = {
		{
			.name = "ina226",
			.i2c_addr = "0x41",
			.bus_number = 1,
			.shunt_value = 0.0008f,
			.started = false,
			.id = "1"
		},
		{
			.name = "ina226",
			.i2c_addr = "0x40",
			.bus_number = 1,
			.shunt_value = 0.0005f,
			.started = false,
			.id = "1"
		},
		{
			.name = "ina238",
			.i2c_addr = "0x8A",
			.bus_number = 1,
			.shunt_value = 0.0003f,
			.started = false,
			.id = "1"
		},
		{
			.name = "ina226",
			.i2c_addr = "0x41",
			.bus_number = 2,
			.shunt_value = 0.0008f,
			.started = false,
			.id = "2"
		},
		{
			.name = "ina226",
			.i2c_addr = "0x40",
			.bus_number = 2,
			.shunt_value = 0.0005f,
			.started = false,
			.id = "2"
		},
		{
			.name = "ina238",
			.i2c_addr = "0x8A",
			.bus_number = 2,
			.shunt_value = 0.0003f,
			.started = false,
			.id = "2"
		}
	};
```

2025-05-01 04:32 UTC, julianoes commented
@niklaut would it work at all with just setting the param to 0.0003 if we detect a Skynode? As pushed in [e22a6e1](https://github.com/PX4/PX4-Autopilot/pull/22051/commits/e22a6e1f3547215b02613dd6af0e24a92a802f6e)?

2025-05-05 00:55 UTC, julianoes commented
@MaEtUgR any chance you could check this?

2025-05-07 22:32 UTC, julianoes commented
@bresch anyone at Auterion that could check my latest changes here?

2025-05-09 11:32 UTC, niklaut requested changes
FMUv5x also needs to have this defaulted to be backward compatible.

2025-05-11 21:47 UTC, julianoes commented
Thanks @niklaut. I will add it for v5x.

2025-05-14 23:04 UTC, julianoes commented
Thanks @niklaut!

2025-05-14 23:04 UTC, merged