MC rate control: let the user set P gain to 1 to use K instead
PX4/PX4-Autopilot pull request #22353
Opened 2023-11-13 10:27 UTC by bresch

### Solved Problem
To tune the PID controller using the standard/ideal form, one needs to set the P gain to 1.
Fixes https://github.com/PX4/PX4-Autopilot/issues/22170

### Changelog Entry
For release notes:
```
Fix multirotor P gain limit for KID tuning
```

2023-11-13 11:25 UTC, MaEtUgR requested changes
I imagine a user following the step-by-step guide tuning his first PX4 vehicle. The default gains are a good start for that.  In case he decides to use the KID scaling he's in my eyes best off leaving P at default and tuning KID which is also what the tuning tuning UI does. Because in case he decides to set P to 1 he configures a gain ~7 times higher than the default. To correct for this a user might set K to 0.15 (default P). Now the I and D values are ~7 times too low so the I gain need to be set ~1.4 and D gain ~0.021 just to arrive at the same default gains which I'd recommend to start out with.

We need to only give options when there is an advantage and not just a potential knive to run into. Either we keep it as is and encourage users to stay with the default P gain value or we change to KID completely but I wouldn't leave the docs hinting at setting P to 1 without further details and just increase the maximum to make that possible.

2023-11-14 20:39 UTC, dagar commented
It seems like it would have been cleaner and safer to do one or the other (or both separately) even though it was "easy" to support both in one module.

2023-11-15 09:10 UTC, bresch commented
Otherwise, one thing we could do is to have a param to select between PID and KID that automatically does the conversion for the user. This would probably by easier to use and less error prone.

2023-11-15 21:32 UTC, dagar commented
What about going all in on KID only and figure out how to safely migrate existing setups?

2023-11-16 08:33 UTC, bresch commented
> What about going all in on KID only and figure out how to safely migrate existing setups?

I'm totally in favor of this but @MaEtUgR or @bkueng might have another opinion.

2023-11-16 09:07 UTC, MaEtUgR commented
I personally prefer independent PID gains because I want to individually tune the terms. It's how I learned it from lectures and successfully applied it in practical workshops, hobby projects and all PX4 tunings. I only ever saw the need to scale all gains and use K when the output scale (unit thrust -> actual physical effect) was off or changed independently of everything else.

If the user wants to spend minimal time and doesn't know how to tune the individual terms there's certainly an advantage to having only one knob to adjust for the output scaling and leave the ratio between the terms to the default. That's also why I taught it this way at the dev summit.

Proper tuning procedure: PID
Beginner one knob/output scaling: change K only

If you are not convinced why scaling the other terms with P/K is not globally useful here is a helicopter tuning:
```
MC_PITCHRATE_FF 0.36
MC_PITCHRATE_P 0.05
MC_PITCHRATE_I 0.3
MC_PITCHRATE_D 0.002
```
I and D ended up close to default but P is completely different in that case. Some multicopters also need a different ratio specific to some design decisions. If P ends up to be much lower or higher than default I and D have to constantly be compensated for this. That's the main reason I'm holding on to these individual gains.

How about we document that K adjusts for the output scaling and is beginner friendly, PID are the gains if you want to spend the extra effort to account for vehicle specifics?

2023-11-16 09:09 UTC, MaEtUgR commented
If that's too confusing for the users and we are keeping complexity for 1% of the users then we can of course switch to KID, lose one parameter and I know how to rescale manually for helicopters and airframes with less typical dynamics.

2026-08-10 02:15 UTC, closed without merging