Manual Control Input via UDP
PX4/PX4-Autopilot pull request #22406
Opened 2023-11-18 09:58 UTC by christianrauch

This PR adds a new module `mc_in_udp` that listens on a UDP port for a list of float values that are translated into `manual_control_setpoint_s` messages and published on uORB topic `manual_control_input`. It can be used for remote control without MAVLink.

The message format, including a simple example client in Python, is documented in the README. 

### Changelog Entry
For release notes:
```
Feature "Manual Control Input via UDP" (mc_in_udp)
```

### Test coverage
Tested with C++ and Python clients using jMAVSim with SITL.

2023-11-18 11:48 UTC, christianrauch commented
How do I fix the issue `NameError: name 'default_port' is not defined` that is [reported by the CI](https://github.com/PX4/PX4-Autopilot/actions/runs/6913252582/job/18809898685?pr=22406)? It's clearly defined as type `in_port_t` here https://github.com/PX4/PX4-Autopilot/blob/291a561d510347890aefa59f05930c6730f3714b/src/drivers/mc_in_udp/mc_in_udp.cpp#L46 and passes compilation.

2023-11-18 18:25 UTC, AlexKlimaj commented
How is this different than manual control input on UDP over mavlink? Smaller packets?

2023-11-18 19:13 UTC, christianrauch commented
> How is this different than manual control input on UDP over mavlink? Smaller packets?

The package size was not the main motivation. But if you want to know, it's between 22 and 46 bytes, depending on how many AUX channels you send.

Compared to MAVLink, this has much fewer dependencies and is easier to set up. See the Python example client.

2023-11-19 15:57 UTC, dagar requested changes
Could you please change the naming, we've always used `mc` to consistently mean `multicopter`.

2023-11-19 16:05 UTC, dagar commented
I personally think most people should be using either mavlink, uxrce_dds, or zenoh for this and if dependencies/complexity are truly an issue we could figure out how to make that more palatable. That being said I'm also not opposed to a super simple standalone example like this, let's just make sure it's not confused with anything else.

 - `mc` should be reserved for `multicopter`
 - could you move this to src/examples (at least initially) and name it something descriptive (eg simple_udp_manual_input)? I want to be careful not to add more confusion if people stumble across things in the code base.

2023-11-20 12:09 UTC, PetervdPerk-NXP commented
Since you're specifying an UDP protocol message. Can you include also the endianness of the bytes and the method to represent the float (ie. IEEE 754).

Different CPU architectures can misread the message because of that.

2023-11-21 19:11 UTC, christianrauch commented
> I personally think most people should be using either mavlink, uxrce_dds, or zenoh for this and if dependencies/complexity are truly an issue we could figure out how to make that more palatable. That being said I'm also not opposed to a super simple standalone example like this, let's just make sure it's not confused with anything else.
> 
> * `mc` should be reserved for `multicopter`
> * could you move this to src/examples (at least initially) and name it something descriptive (eg `examples/simple_udp_manual_input`)? I want to be careful not to add more confusion if people stumble across things in the code base.

I am fine with the renaming. However, I don't think "example" is a good fit. It would be an example for what? I think this module is somewhat similar to `rpi_rc_in`. This module reads RC channels via shared memory and publishes them on uORB topics without the need for real hardware.

2023-11-21 19:19 UTC, christianrauch commented
> Since you're specifying an UDP protocol message. Can you include also the endianness of the bytes and the method to represent the float (ie. IEEE 754).
> 
> Different CPU architectures can misread the message because of that.

I added this to the documentation.

2023-11-22 16:23 UTC, dagar commented
I pulled the Mac OS CI change into main. https://github.com/PX4/PX4-Autopilot/commit/1cf38e9d762c92f7624ee8b2e0a3b40cbfa0477e

2023-11-23 02:35 UTC, dagar commented
> > I personally think most people should be using either mavlink, uxrce_dds, or zenoh for this and if dependencies/complexity are truly an issue we could figure out how to make that more palatable. That being said I'm also not opposed to a super simple standalone example like this, let's just make sure it's not confused with anything else.
> > 
> > * `mc` should be reserved for `multicopter`
> > * could you move this to src/examples (at least initially) and name it something descriptive (eg `examples/simple_udp_manual_input`)? I want to be careful not to add more confusion if people stumble across things in the code base.
> 
> I am fine with the renaming. However, I don't think "example" is a good fit. It would be an example for what? I think this module is somewhat similar to `rpi_rc_in`. This module reads RC channels via shared memory and publishes them on uORB topics without the need for real hardware.

It's not the best naming/solution at the moment, but it's more of a place we can keep experiments off to the side until they're fully supported. This isn't being built or tested on any boards, no testing in CI, and for now the "official" recommendation for manual control should still be mavlink, and XRCE DDS.

2023-11-29 19:01 UTC, christianrauch commented
@dagar I renamed the module and moved it to the examples. Is this ok now? Other than this, I am only left with the CI telling me that `default_port` is undefined: https://github.com/PX4/PX4-Autopilot/pull/22406#issuecomment-1817487060.

2025-01-28 13:17 UTC, christianrauch commented
@dagar Can you have a look at this again? The remaining CI issue (`failed to push ghcr.io/px4/px4-dev:v1.16.0-alpha2-281-ge33137e632: unexpected status from POST request to https://ghcr.io/v2/px4/px4-dev/blobs/uploads/: 403 Forbidden`) is unrelated to this PR.

2025-10-08 22:28 UTC, christianrauch commented
@dagar @bkueng Since this PR is adding an example and not touching other files in the project, it should be quick to review. Can you please have a look at this now?

2025-10-08 22:51 UTC, hamishwillee commented on src/examples/manual_control_input_udp/README.md
> +This module listens to manual control messages on a UDP port and republishes them to uORB topic `manual_control_input`. The UDP port (default: `51324`) can be set via parameter `p`.
My understanding is that this demonstrates how a driver can monitor the UDP port, parse an input stream, and publish to a uORB topic. It happens to use the example of parsing a MAVLINK_CONTROL message and writing to the `manual_control_input` topic (defined in [ManualControlSetpoint](https://docs.px4.io/main/en/msg_docs/ManualControlSetpoint.html#).

Thoughts:
- What does this example show that is not shown in other examples?
- Its an example. Is everything else about the example best-practise - including documentation etc.
- Should the docs of this be in the user guide, along with an explanation of the code?
- Is the example tested - if the interface changes for the uorb topic, when would we find out?
- This is not the way you would normally handle the input of this mavlink message - we do it in the mavlink module. We should spell out what this shows, what it is for, and this limitation.
- `ManualControlSetpoint` is poorly documented. What is the implication of updating the topic `manual_control_input` and how does this differ from updating `manual_control_setpoint`? I.e. is this just what MAVLink does now - update the input - and other code then works with the other possible inputs to set the setpoint topic?

I guess the summary is that this is cool, but we should make sure that we make implications clear and look at ways to make sure we know if it ever breaks.

2026-08-10 02:15 UTC, closed without merging