Ignore mission yaw setpoints in `WV_EN` enabled
PX4/PX4-Autopilot pull request #22413
Opened 2023-11-20 14:27 UTC by TedObrien

### Solved Problem
In mission mode or return mode, weather-vaning can cause the drones' heading to change by more than MIS_YAW_ERROR. This causes the drone to remain at its current mission setpoint indefinitely.

Fixes #22355

### Solution
Added a conditional to make `_waypoint_yaw_reached = true` if `WV_EN` is enabled and `position_setpoint.disable_weather_vane=false`

### Test coverage
- Tested in sitl with the windy environment. 
- Ran a mission specifying yaw setpoints at each waypoint
- with `WV_EN=1` vehicle ignored yaw setpoints and completed the mission pointing into the wind (https://review.px4.io/plot_app?log=f0720db6-dd2e-486d-8d38-dfa08e58048f)
- with  `WV_EN=0` the vehicle follows yaw setpoints specified in the mission (https://review.px4.io/plot_app?log=f95a52a1-3710-491d-a8d1-3655c709ccb9)

2023-11-21 16:41 UTC, danielhonies requested changes
(_navigator->get_weathervane_enabled() == true) && (pos_sp_triplet->current.disable_weather_vane == false) -> _navigator->get_weathervane_enabled() &&  ! pos_sp_triplet->current.disable_weather_vane

2023-11-21 16:42 UTC, danielhonies commented
Thanks for the PR, I would recommend to write this one line a bit cleaner.

2023-11-22 09:54 UTC, TedObrien commented
Good call, just modified that line.

Thanks

2023-11-28 11:11 UTC, sfuhrer commented
Can you first make the PR again `main`? And then we can port it to the release branch (1.14) as well. 

I'm curious for the use case: why do you want to specify yaw angles at the waypoints AND enable weather-vane? And shouldn't in that case the right thing be to fix the broken `position_setpoint.disable_weather_vane` reporting (if the waypoint enforces a yaw then this setpoint flag should be set to true )?

2023-11-28 17:29 UTC, TedObrien commented
Hello, I encountered a problem initially (#22355), where the drone would sometimes loiter indefinitely during RTL due to the heading not meeting the acceptable yaw error (caused by weather-vaning). Although my usage doesn't involve setting specific yaw angles at mission waypoints, RTL mode appears to use mission setpoints with specified yaw angles that prevents the drone's progression to the next phase of RTL.

For context, my application involves a multi-copter equipped with an anemometer, requiring alignment with the wind direction.  Using `position_setpoint.disable_weather_vane` for landing purposes works well in this scenario. However, for a vehicle with a lifting surface, maintaining the current heading into the wind during RTL might be more appropriate.

Hopefully this makes sense, I'll redo the PR on main.

Thanks

2023-11-29 10:03 UTC, TedObrien commented
Just made a new PR from main #22455

2023-12-21 15:50 UTC, closed without merging