L1 bug - fix Crosstrack Error angle calculation in ECL_L1_Pos_Controller.cpp
PX4/PX4-Autopilot pull request #22425
Opened 2023-11-21 16:53 UTC by slgrobotics

"vector_A_to_airplane" should be normalized for proper angle calculation

### Solved Problem
L1 algorithm allows a vehicle to closely follow a line between two waypoints (A and B).
In current code there is a calculation of an angle between A-P line and A-B line (P being current position).
It can be queried using crosstrack_error() method, and cab be used by a consumer to calculate crosstrack distance (how far from the A-B line the vehicle is).
It is important to have these calculations done correctly, as some vehicles in agricultural and survey areas have to stick to scan lines precisely.

### Testing
I tested the correction in SITL and live in my lawnmower robot.

2023-11-21 17:32 UTC, slgrobotics commented
@PerFrivik  - I also don't like line 163 there. Seems to have the same bug. We probably should calculate "vector_A_to_airplane_unit" earlier and use it for angles.

2023-11-21 19:05 UTC, slgrobotics commented
One more thing. L1 never quite worked for me in its original form. Currently I just call it to compute crosstrack error (angle), and then use simple math to compute crosstrack distance (meters from the AB line). Then I have a "Line Following PID" to minimize that distance, which feeds Rate Controller to stabilize turning to the line. That allow vehicle to stick to the line much better.

2023-11-22 16:27 UTC, bresch requested changes
The crosstrack error is the minimum distance between the drone and the line segment between A and B. The cross product of `X % Y = X.norm() * Y.norm() * sin(theta)` where theta is the angle between the two vectors, meaning that since `vector_AB` is unit, `vector_AB % vector_A_to_airplane` is the correct crosstrack error.

2023-11-22 17:19 UTC, closed without merging

2023-11-22 17:35 UTC, slgrobotics commented
@brech - true. My bad. 

My customized RoverPositionControl.cpp code was based on a ~2019 "main" version, and somehow treated crosstrack_error as angle, and then calculated crosstrack_dist. I couldn't track that line down though. Possibly just my bug while experimenting. Sorry for wasted time.

2023-11-23 12:37 UTC, bresch commented
No worries!