Add offboard mode switch module for simplifying offboard for ros2
PX4/PX4-Autopilot pull request #22530
Opened 2023-12-12 20:34 UTC by Jaeyoung-Lim

Wip add offboard switch module

### Solved Problem
When ... I found that ...

Fixes #{Github issue ID}

### Solution
- Add ... for ...
- Refactor ...

### Changelog Entry
For release notes:
```
Feature/Bugfix XYZ
New parameter: XYZ_Z
Documentation: Need to clarify page ... / done, read docs.px4.io/...
```

### Alternatives
We could also ...

### Test coverage
- Unit/integration test: ...
- Simulation/hardware testing logs: https://review.px4.io/

### Context
Related links, screenshot before/after, video

2023-12-17 17:35 UTC, beniaminopozzan commented
@Jaeyoung-Lim The idea here is that the new module monitors the `offboard_*` topic, and if they are valid then it publishes the `offboard_control_mode` topic and only when the vehicle enter `OFFBOARD` mode then the `offboard_*` topics republished standard setpoints? Did I get it right?

2023-12-17 17:51 UTC, Jaeyoung-Lim commented
@beniaminopozzan Yes, plus it handles the offboard_mode handling. So the offboard node doesnt necessarily need to publish this

2023-12-17 20:31 UTC, beniaminopozzan commented
Great, is there a reason for having only the logic for trajectory, attitude and rate setpoint? what about thrust and torque and direct?

2023-12-18 04:08 UTC, Jaeyoung-Lim commented
> about thrust and torque and direct?

@beniaminopozzan No real reason, just wasnt able to test with it yet

One thing missing from this is sanity checking the combination of setpoints (e.g. you cant set thrust and torque with rates at the same time)

2024-01-09 16:57 UTC, dagar commented on src/modules/offboard_switch/CMakeLists.txt
> +#   Copyright (c) 2015 PX4 Development Team. All rights reserved.
```suggestion
#   Copyright (c) 2024 PX4 Development Team. All rights reserved.
```

2024-01-09 17:05 UTC, MaEtUgR commented on src/modules/offboard_switch/offboard_switch.hpp
> +
```suggestion
```

2024-01-09 17:05 UTC, MaEtUgR commented on src/modules/offboard_switch/offboard_switch.cpp
> +// }
```suggestion
```

2024-01-30 16:51 UTC, mrpollo commented
@MaEtUgR we are still waiting on your review!

2024-01-30 17:40 UTC, beniaminopozzan requested changes
The is no `offboard_thrust_setpoint`, `offboard_torque_setpoint` and `offboard_actuator_motor_setpoint` yet
I suggest to mark the PR as _draft_ until it is ready

2024-01-30 19:16 UTC, Jaeyoung-Lim commented
@beniaminopozzan I have intentionally left them out, since I think for those I think it might be just better to publish directly to the actuators due to the time delay introduced by publishing/republishing

2024-02-05 09:18 UTC, Jaeyoung-Lim commented
> Wouldn't it be cleaner at this point, instead of having a centralized offboard mode swither, to distribute this on every module that uses the "setpoint" messages?
Something like: if mc_att_control subcribes to vehicle_attitude_setpoints, then it will subscribe to offboard_attitude_setpoint too. Internally it will use offboard_attitude_setpoint instead of vehicle_attitude_setpoints if vehicle_control_mode says offboard + attitude.

I have been trying to avoid this, as by doing this we would create a new "flight mode" for offboard mode and all controller modules need to be aware of the "offboard" interface. For me the value of offboard mode is that the control modules do not know whether the vehicle is in offboard mode and therefore we can test individual structures by simply turning on and off different levels of control handled by commander. If somebody is implementing a new controller, they do not need to implement a special "offboard" interface to test it.

Regarding completeness, I agree with you that it would be nice to support direct actuator setpoints. However, this PR solves a problem where a lot of people are struggling to use the offboard interface due to the "handshaking" behavior it requires(need to monitor vehicle flight mode before publishing the setpoints). The people struggling to do this are rarely people using direct actuator inputs.

On the other hand, I do not have the capacity to test the direct actuator setpoint interface for this PR. So if anyone would be interested in contributing it would be great but otherwise, it will be hard to include it as part of this PR.

2026-06-26 13:27 UTC, Jaeyoung-Lim commented
Closing as stale

2026-06-26 13:27 UTC, closed without merging