matrix: fix quaternion calculation
PX4/PX4-Autopilot pull request #22934
Opened 2024-03-27 00:06 UTC by julianoes

2024-03-27 01:09 UTC, dagar commented
Catch it in the unit test? 

https://github.com/PX4/PX4-Autopilot/blob/3f61972fb3adb4ad28ee734cf8bcf752c1aaf026/src/lib/matrix/test/MatrixAttitudeTest.cpp#L73-L96

2024-03-27 01:22 UTC, julianoes commented
It seems to fail the tests, so I wonder who is right, the unit test or the implementation.

2024-03-28 11:07 UTC, bresch requested changes
I think the `+` is correct (see https://raw.org/proof/quaternion-from-two-vectors/), where did you find the `/` solution?

2024-03-28 11:08 UTC, Seungwon-Yeo commented
Dooray! 메일 발송 실패 안내



  
  
    
    
  
  
    
메일 발송
실패 안내
    
  
  
    
        
          
***@***.***) 
          님께
보낸
메일이
전송되지
못하였습니다.
        
        
          실패 사유를 확인해보세요.
        
    
  
  
    
      
        
          
            * 받는 사람 : 
***@***.***) 
          
          
            * 발송 시간 : 
2024-03-28T20:08:05
          
          
            * 메일 제목 : 
Re: [PX4/PX4-Autopilot] matrix: fix quaternion calculation (PR #22934)
          
          
            
              
                * 실패 사유 : 
              
              
                
대외비/기밀 메일은 외부 계정으로 발송이 제한되어 일부 메일 발송 실패(수신자가 전달 설정한 경우 포함)
                
              
            
                      
          
        
      
    
  
  
    
        
          이 메일은 발신전용으로 회신되지 않습니다.
          더 궁금하신 사항은
          ***@***.***
          으로 문의해 주시기 바랍니다.
        
    
  
  
    
        © Dooray!.

2024-04-04 03:07 UTC, julianoes commented
Thanks for checking @bresch!

2024-04-04 03:07 UTC, closed without merging