ekf optical flow only compensate to a lower value
PX4/PX4-Autopilot pull request #23046
Opened 2024-04-22 18:48 UTC by AlexKlimaj

This PR is an attempt to remove fake velocity oscillations for the optical flow data. Where there is 0 or little pixel flow, the gyro noise oscillations dominate the optical flow velocity output.

Continuation of https://github.com/PX4/PX4-Autopilot/pull/22095

@dirksavage88 

![image](https://github.com/PX4/PX4-Autopilot/assets/2019539/fcde1c30-0412-498d-9f7c-a5082df74e20)

![image](https://github.com/PX4/PX4-Autopilot/assets/2019539/d50fd72e-1047-4053-90ab-f12d76c202c1)

2024-04-22 19:15 UTC, dirksavage88 commented
Will test this very soon @AlexKlimaj

2024-04-24 08:14 UTC, bresch requested changes
Let's assume you have a flow rate of 1rad/s and zero-mean gyro data with noise. If you simply subtract them, you'll get 1rad/s flow with noise. However, if you use your conditional subtraction, you'll get a signal with a mean < 1rad/s and some noise.

2024-04-24 19:48 UTC, dagar commented
If we want to play with these ideas let's get a replayable log with GPS (or another reliable velocity/position source) at a few different altitudes.

2024-04-26 15:58 UTC, dirksavage88 commented
![gyro_comp_fixes](https://github.com/PX4/PX4-Autopilot/assets/35986980/9a6bfbf0-4bc1-44da-a968-13da41135dcc)

2024-04-29 20:46 UTC, AlexKlimaj commented
Not sure if my conditional subtraction is working.

https://review.px4.io/plot_app?log=960fafa5-0818-4d50-96be-42134be18775

2024-04-29 20:52 UTC, dirksavage88 commented
I noticed the oscillations are far worse above 3m

2024-05-01 16:05 UTC, closed without merging