commander: add check for 5V overvoltage
PX4/PX4-Autopilot pull request #23147
Opened 2024-05-17 08:12 UTC by bkueng

2024-05-17 09:27 UTC, bresch requested changes

2024-05-17 09:27 UTC, bresch commented on src/modules/commander/HealthAndArmingChecks/checks/powerCheck.cpp
> +						       events::Log::Error, "Overvoltage detected for the hipower 5V supply");
Isn't it "overcurrent" ?

2024-05-21 07:25 UTC, bkueng commented on src/modules/commander/HealthAndArmingChecks/checks/powerCheck.cpp
> +						       events::Log::Error, "Overvoltage detected for the hipower 5V supply");
:facepalm: of course

2024-05-21 11:49 UTC, bresch approved these changes

2024-05-22 07:34 UTC, merged