Fix fmu rc_input on v5x and v6x
PX4/PX4-Autopilot pull request #23175
Opened 2024-05-23 12:55 UTC by DanielePettenuzzo

As far as I can see fmu v5x and fmu v6x are not designed to have rc_input as a single wire uart.

### Solved Problem
This PR disables this for both targets and fix my issue where RC works only through the px4io but not directly to the fmu.

### Changelog Entry
For release notes:
```
Bugfix for rc_input when connecting the RC receiver directly to the FMU (no px4io)

```

### Test coverage
- Tested on Auterion Skynode with both FMU V5X and FMU V6X

2024-05-23 18:31 UTC, davids5 requested changes
IIRC 

USART6_RX_FROM_IO__RC_INPUT
USART6_TX_TO_IO__RC_NC

Are the signals involved.  Single wire defaults to Using TX for both directions unless you enable [RC_SERIAL_SWAP_RXTX](https://github.com/PX4/PX4-Autopilot/blob/4f64acb3524d39967bd7f516ae2ebfe4be5246bc/platforms/common/include/px4_platform_common/board_common.h#L491).

I am not sure how that got dropped.

2024-07-08 08:18 UTC, niklaut submitted a review, later dismissed
Please merge.

2024-09-03 11:03 UTC, davids5 commented
The issue with this is that on base without an PXI4O the UART that connects to the IO will be used on that line in single wire mode.
So this will break all the bases without an IO. Could be what you experienced be a setting related issue?

2024-09-17 12:33 UTC, niklaut commented
Hm? This fixes an issue with Skynode Lite, which does not have an PX4IO.

2024-09-18 17:42 UTC, davids5 commented
@niklaut did you test this on a base with and without an PX4IO?

2024-09-19 09:05 UTC, niklaut commented
Yes, these changes have been tested on a Skynode Lite v5x (without PX4IO) and a Skynode X v6x (with PX4IO).

2024-09-19 14:11 UTC, davids5 approved these changes

2024-09-25 13:57 UTC, merged