Orbit Yaw Vehicle Parameter
PX4/PX4-Autopilot pull request #23358
Opened 2024-07-03 13:05 UTC by Claudio-Chies

### Solved Problem
then a vehicle type, for which the orientation is relevant, performs an orbit maneuver, e.g a Tricopter the orientation during the orbit had to be hardcoded.

### Solution
To solve this problem i introduce an Parameter called MC_ORBIT_YAW_MOD, which gets used for setting the orbit yaw behavior on the vehicle side.
when no ORBIT_YAW_BEHAVIOUR is sent with the MAV_CMD_DO_ORBIT command, it now uses the vehicle default orbit behavior.
Relevant other changes:
QGC: change of default orbit yaw behavior to NaN.

### Changelog Entry
For release notes:
```
Feature/Bugfix Added vehicle specific yaw behavior
New parameter: MC_ORBIT_YAW_MOD
Documentation: Need to clarify page ... / done, read docs.px4.io/...
```

### Test coverage
Tested in SITL

2024-07-04 00:58 UTC, hamishwillee commented on src/modules/flight_mode_manager/tasks/Orbit/flight_task_orbit_params.c
> + * Yaw behaviour during orbit flight.
Perhaps include "default" to make it clear this can be overridden.

```suggestion
 * Default yaw during orbit.
```

2024-07-22 10:07 UTC, Claudio-Chies commented
implemented changes requested in https://github.com/mavlink/mavlink/pull/2132
when the ORBIT_YAW_BEHAVIOUR_UNCHANGED enum is set in MAV_CMD_DO_ORBIT. Then, if the multicopter is currently orbiting, it will keep its current yaw behaviour if another MAV_CMD_DO_ORBIT is sent. 
if its not orbiting, it will read the new yaw behaviour from the parameter

2024-07-23 07:48 UTC, bresch requested changes

2024-07-23 07:48 UTC, bresch commented on src/modules/flight_mode_manager/tasks/Orbit/FlightTaskOrbit.cpp
> +		if (command.param3 - 5.0f < FLT_EPSILON) {
To be a bit more explicit you could do as in here: https://github.com/PX4/PX4-Autopilot/blob/36d89df0a722e2fca3f23e4d0ddd9da9fb5b7ecc/src/modules/flight_mode_manager/FlightModeManager.cpp#L318
And define the `ORBIT_YAW_BEHAVIOUR_UNCHANGED` in [vehicle_command](https://github.com/PX4/PX4-Autopilot/blob/36d89df0a722e2fca3f23e4d0ddd9da9fb5b7ecc/msg/VehicleCommand.msg#L155-L159)

2024-07-29 07:29 UTC, bresch approved these changes

2024-07-29 07:29 UTC, bresch commented on src/modules/flight_mode_manager/tasks/Orbit/FlightTaskOrbit.hpp
> +#include <uORB/topics/vehicle_command.h>
`applyCommandParameters(const vehicle_command_s &command, bool &success)` also required `vehicle_command.h`, do you really need to re-include it here? How did it work before?

2024-08-06 14:12 UTC, bresch approved these changes

2024-08-07 09:12 UTC, merged