only warn once when the last mag fails/gets disabled
PX4/PX4-Autopilot pull request #23425
Opened 2024-07-18 14:21 UTC by haumarco

### Solved Problem
When the the last mag fails and there is no mag left to switch to, the current implementation keeps sending warnings to the user every 3 seconds.

### Solution
If the mag continues to fail, no new warning gets sent. It still works correctly for:
mag works -> mag fails (warns) -> mag fails -> mag works -> mag fails (warns)

2024-07-18 14:26 UTC, haumarco commented
We could also adjust the [DataValidatorGroup::get_best()](https://github.com/PX4/PX4-Autopilot/blob/main/src/modules/sensors/data_validator/DataValidatorGroup.cpp#L140) to not increment the `_toggle_count` of the validator. But then we would need to first clarify if that would also be desired for the VehicleAirData check.

2024-07-18 18:41 UTC, dagar commented
We definitely don't want anything repeatedly spamming text messages. At most it should error on the transition, and in many cases I'm not even sure it should be an error message (vs logged in another msg) unless it's truly critical.

2024-07-18 22:11 UTC, dagar commented
> We could also adjust the [DataValidatorGroup::get_best()](https://github.com/PX4/PX4-Autopilot/blob/main/src/modules/sensors/data_validator/DataValidatorGroup.cpp#L140) to not increment the `_toggle_count` of the validator. But then we would need to first clarify if that would also be desired for the VehicleAirData check.

This sounds like the better fix, if it only increased on actual changes everything would work the way we want right?

2024-07-22 14:40 UTC, bresch requested changes
Why do you need that extra protection against spamming? If the `max_index == _curr_best` then there is no additional failsafe and it shouldn't throw any additional message.

2024-07-22 14:40 UTC, bresch commented on src/modules/sensors/data_validator/DataValidatorGroup.hpp
> +	int8_t _last_failover_index{-1}; /**< index of the last failover */
```suggestion
	int8_t _last_failover_index{-1};
```
what else could it be?

2024-07-22 14:40 UTC, bresch commented on src/modules/sensors/data_validator/DataValidatorGroup.hpp
> +	int8_t _last_failover_index{-1}; /**< index of the last failover */
Please don't follow that bat habit of commenting every line https://youtube.com/clip/UgkxcPLMW6uiLRvBmoKkDP7jm0ntYxDyaxLS?si=TKwknK0o-JEvR7cN

2024-07-23 07:21 UTC, bresch approved these changes
@haumarco Did you test this on hardware?

2024-07-24 09:24 UTC, merged