Update GZBridge to be able to use gazebo airspeed. Add quadtailsitter.
PX4/PX4-Autopilot pull request #23455
Opened 2024-07-26 04:40 UTC by jmackay2

### Solved Problem
When adding a gz tailsitter, I found out that the current airspeed simulation is hard-coded to use the body velocity in the x direction. This doesn't work for the tailsitter, where the airspeed sensor needs to be rotated by 90 degrees to work correctly in fixed-wing flight. 

### Solution
This uncomments the gazebo airspeed integrations in the GZBridge and adds minor fixes to work correctly. This also adds a gazebo quadtailsitter configuration. 

### Changelog Entry
For release notes:
```
Feature: Adds the capability to use the Gazebo airspeed sensor and adds a Gazebo quadtailsitter.
```

### Test coverage
- Simulation of the standard_vtol model in gazebo.
- Simulation of the quadtailsitter. The quadtailsitter in fixed-wing is very fast and probably needs a little more modifications to be more realistic.

2024-07-26 06:48 UTC, Jaeyoung-Lim requested changes

2024-07-26 06:48 UTC, Jaeyoung-Lim commented on ROMFS/px4fmu_common/init.d-posix/airframes/4004_gz_standard_vtol
> -param set-default SENS_EN_BAROSIM 0
Why remove the barometer?

2024-08-18 10:43 UTC, Jaeyoung-Lim approved these changes
LGTM!

2024-08-18 13:47 UTC, Jaeyoung-Lim commented
@jmackay2 Could you rebase the PR so we can see if the SITL failures are real?

2024-08-19 06:54 UTC, Jaeyoung-Lim approved these changes
Thanks!

2024-08-19 06:54 UTC, merged

2024-08-19 09:38 UTC, daeyeonk commented
Is this causing "make px4_sitl" to fail?

In file included from /root/PX4-Autopilot/src/modules/simulation/gz_bridge/GZBridge.cpp:34:
/root/PX4-Autopilot/src/modules/simulation/gz_bridge/GZBridge.hpp:105:47: error: 'AirSpeed' in namespace 'gz::msgs' does not name a type
  105 |         void airspeedCallback(const gz::msgs::AirSpeed &air_speed);
      |                                               ^~~~~~~~
compilation terminated due to -Wfatal-errors.
[1025/1038] Building CXX object src/modules/mavlink/CMakeFiles/modules__mavlink.dir/mavlink_messages.cpp.o
ninja: build stopped: subcommand failed.
make: *** [Makefile:232: px4_sitl] Error 1

2024-08-20 01:34 UTC, daeyeonk commented
> > Is this causing "make px4_sitl" to fail?
> > In file included from /root/PX4-Autopilot/src/modules/simulation/gz_bridge/GZBridge.cpp:34: /root/PX4-Autopilot/src/modules/simulation/gz_bridge/GZBridge.hpp:105:47: error: 'AirSpeed' in namespace 'gz::msgs' does not name a type 105 | void airspeedCallback(const gz::msgs::AirSpeed &air_speed); | ^~~~~~~~ compilation terminated due to -Wfatal-errors. [1025/1038] Building CXX object src/modules/mavlink/CMakeFiles/modules__mavlink.dir/mavlink_messages.cpp.o ninja: build stopped: subcommand failed. make: *** [Makefile:232: px4_sitl] Error 1
> 
> It certainly sounds like it. What version of Gazebo are you using and what version of gz-sensors and gz-msgs do you have? Airspeed should have come into gz sensors and msgs about a year ago.
> 
> I see the air-speed library in gz-sensors in the latest gz versions: 7.3.0, and 8.2.0. I do not see it in gz-sensors 6 though.

I am using bash ./PX4-Autopilot/Tools/setup/ubuntu.sh for 22.04

2024-08-20 14:59 UTC, dagar commented
We need to do something to keep builds working on 22.04.

2024-08-21 04:34 UTC, hamishwillee commented
So this didn't go in? Worth still fixing the tiny bug:

<img width="529" alt="image" src="https://github.com/user-attachments/assets/b5a0c09f-0c36-4aa7-9fcd-cade22359d72">

2024-08-21 12:02 UTC, Jaeyoung-Lim commented
We should probably switch to harmonic since that is the LTS. However, this would mean that we explicitly state that we are going to make a breaking change.