Add maximum height above ground (HAGL) check to all Navigator modes
PX4/PX4-Autopilot pull request #23542
Opened 2024-08-14 12:46 UTC by bresch

### Solved Problem
The HAGL navigator failsafe I added in https://github.com/PX4/PX4-Autopilot/pull/23501 should be used in all navigator modes.

### Solution
Centralize the check instead of adding it to each mode separately.

### Changelog Entry
For release notes:
```
Add maximum height above ground (HAGL) check to all Navigator modes
New parameter: -
Documentation: -
```

### Test coverage
- SITL tests

2024-08-15 14:07 UTC, sfuhrer requested changes
Agree that we should aim for a generic solution and not have them custom for RTL/Takeoff. Some comments from testing in SITL:
- the reporting of the HAGL failsafe is a bit rough. E.g. it says it will switch to Hold when it already is in Hold, and it doesn't apply the timeout
![image](https://github.com/user-attachments/assets/3e5b7c4c-cede-47e2-8d94-c49fdb4fd4de)
- doesn't seem to work with MC Orbit
- RTL wih OF only: why does it 3 times switch into RTL before then going to Land?
![image](https://github.com/user-attachments/assets/1076c700-b6e9-4e2d-b8a8-5636050d36c1)

2024-08-16 09:05 UTC, bresch commented on src/modules/navigator/mission_block.cpp
> +		// Handle case where the takeoff altidude is above the maximum HAGL
Hmm, that's a good example why comments are bad

2024-08-16 09:09 UTC, bresch commented on src/modules/navigator/mission_block.cpp
> +		events::send(events::ID("navigator_takeoff_fail_max_hagl"), events::Log::Error, "Target altitude higher than max HAGL");
thanks

2024-08-16 13:34 UTC, sfuhrer approved these changes
Looks good to me now, the extension to not have the delay when switching to Hold seems correct. For my other comments:

>doesn't seem to work with MC Orbit

Okay that is expected and not easy to change, as the Orbit doesn't use the triplet at all

> RTL wih OF only: why does it 3 times switch into RTL before then going to Land?

That was actually the GCS sending the command 3 times.

2024-08-16 14:26 UTC, merged