Implemented temperature sensor support for INA228 / INA238
PX4/PX4-Autopilot pull request #23639
Opened 2024-09-03 16:04 UTC by alexcekay

### Solved Problem
The INA228 and INA238 sensors have packaged temperature sensors. With this PR it is possible to use the temperature readings from these sensors. They are published in the field "temperature" of "BatteryStatus"

### Solution
- Extended the Battery abstraction to also include a temperature
- Read out the temperature values from the sensors via I2C

### Changelog Entry
For release notes:
```
Feature/Bugfix Added INA228 / INA238 temperature sensor support
```

### Alternatives
When we want to use the temperature measurements of those sensors there is no alternative.

### Test coverage
- Was tested locally at the bench

2024-09-04 15:01 UTC, niklaut requested changes

2024-09-05 11:49 UTC, niklaut commented on msg/BatteryStatus.msg
> +float32 temperature				# Temperature of the battery in degrees Celcius, NaN if unknown
It's too much work to do this properly for this change, so we leave it as is now.

2024-09-05 11:49 UTC, niklaut approved these changes

2024-09-06 03:08 UTC, dagar approved these changes

2024-09-06 03:09 UTC, merged