EKF2: publish wind after external wind init
PX4/PX4-Autopilot pull request #23747
Opened 2024-09-30 15:35 UTC by haumarco

### Solved Problem
EKF-interface only publishes wind data when wind is being estimated, not after being initialized. After setting wind manually over mavlink by using any other external source, this can be confusing for the user.

### Solution
Start publishing wind estimate after wind was set from an external observation...

2024-09-30 15:46 UTC, bresch approved these changes

2024-09-30 17:49 UTC, dagar commented on src/modules/ekf2/EKF2.cpp
> +	if (_ekf.get_wind_status() || _ekf._external_wind_init) {
Really `_external_wind_init` should be private. 

After that does it make sense to push it into get_wind_status()?

2024-10-01 06:13 UTC, sfuhrer reviewed
Isn't there a way to always stream it after being initialized, whether the initialization happened from external or internal?
I expect it's confusing for users to always see the wind stream (also after landing) when they initialized it from external, but not if the system initialized itself.

2024-10-01 07:43 UTC, haumarco commented
I think it's misleading to always publish the wind state even when we're not estimating it and it should be a exception for this use-case. When we set the wind manually we know that we can act as a sensor and change the wind while being landed, otherwise we dont know that.

2024-10-01 09:53 UTC, bresch requested changes
Looks good otherwise.

2024-10-01 09:53 UTC, bresch commented on src/modules/ekf2/EKF/estimator_interface.h
> +	bool _external_wind_init {false};
```suggestion
	bool _external_wind_init{false};
```

2024-10-01 09:53 UTC, bresch commented on src/modules/ekf2/EKF/estimator_interface.h
>  	// get wind estimation status
```suggestion
```
this comment hurts my brain

2024-10-01 10:01 UTC, bresch approved these changes

2024-10-01 12:33 UTC, merged