Add back motor slew rate
PX4/PX4-Autopilot pull request #23835
Opened 2024-10-21 16:52 UTC by MaEtUgR

### Solved Problem
Like @Igor-Misic and me almost simultaneously found out the motor slew rate does not take effect anymore in the dynamic control allocation which is what the mixer now uses for some time:
https://github.com/PX4/PX4-Autopilot/pull/23794
https://github.com/PX4/PX4-Autopilot/pull/23798

I would have been fine with that since I don't think there should be a slew rate on the motor outputs but the ESCs should deal with the feasibility of commands. But in practise they apparently do not always do that and since there are users of this feature I don't want to leave it away.

### Solution
1. I added back a motor slew rate in the motor function (it used to be in the simple and multicopter mixer of the old static mixing) and recovered the `MOT_SLEW_MAX` parameter with its original meaning but a new PWM independent description for backward compatibility. The slew rate reinitializes when there are NAN values in the motor command so they could in theory still jump from NAN to a different value since the motor function does not know what NAN (output protol-specific disarmed value) maps to.
2. I optimized it a bit since depending on the setup if the slew rate is enabled things get called at multiple kilohertz and that has some visible impact on the flight control CPU load e.g. in my test it was ~0.4% difference and not easily visible anymore after the second commit.

### Changelog Entry
```
Feature: Bring back motor slew rate
```

### Alternatives
I would suggest not to use this feature if not urgently necessary but rather make sure:
a) the ESC keeps up stable operation no matter what
b) the sensor noise is filtered adequately to not propagate problems
c) the setpoints are smooth such that there are no crazy jumps in normal operation

### Test coverage
SITL SIH test checking that the timing e.g. 10 seconds from -1 to 1 is correct and the initialization in case of NAN values works.
Real vehicle test to see that on PWM as well as CAN output the same slew rate is percievably in action.

2024-10-22 19:29 UTC, Igor-Misic requested changes
@MaEtUgR you forgote to stage
`(ParamFloat<px4::params::MOT_SLEW_MAX>) _param_mot_slew_max,`
in **mixer_module.hpp**

I've tested it with DShot and works as expected. Thanks!
Code LGTM.

2024-10-23 03:46 UTC, hamishwillee commented
@MaEtUgR This is coming back right? I ask because it is linked in the docs here: https://docs.px4.io/main/en/config_mc/filter_tuning.html#filters

Remember the 11th commandment

> _Ye shall not toucheth a parameter without checking if docs needeth corresponding update._

(or incur the mild disappointment of Hamish)

2024-10-23 17:10 UTC, MaEtUgR commented
I feel stupid 🤦‍♂️ : The feature exists in dynamic control allocation and I didn't know. Plus no one I talked to knew until @sfuhrer who was out showed me 🙏  Previously there was the `MOT_SLEW_MAX` which slews all motors to a minimum time from 0 to 100%. @Igor-Misic rightfully removed it since it had no effect anymore and I wanted to bring it back here. Now there are already per motor `CA_R0_SLEW` and per servo `CA_SV0_SLEW` which do the exact same thing just on the allocation level. I double-checked and the definition is the same.
This pr with `MOT_SLEW_MAX` set to 10 seconds slew rate:
![grafik](https://github.com/user-attachments/assets/d5f39b94-f1f2-4aa2-a676-4a2dc464bd6f)
Main with `CA_R0_SLEW`, `CA_R1_SLEW`, `CA_R2_SLEW`, `CA_R3_SLEW` set to 10 seconds slew rate:
![grafik](https://github.com/user-attachments/assets/87fefaeb-aa68-4ffd-9134-da48cd10c695)
Sorry for wasting people's time, if I only knew 😬

2024-10-23 17:10 UTC, closed without merging

2024-10-23 17:37 UTC, MaEtUgR commented
@hamishwillee Here I took over the parameter description: https://github.com/PX4/PX4-Autopilot/pull/23846
We need to update the guide 😬