Add Linux Mint 21.3 support with Gazebo Harmonic
PX4/PX4-Autopilot pull request #24100
Opened 2024-12-13 01:26 UTC by asifpatankar

### Solved Problem
When executing ubuntu.sh script on Linux Mint 21.3 (based on Ubuntu 22.04), the script failed to recognize the OS and install correct dependencies, particularly for Java and Gazebo. Fixes #24097

### Solution
- Added Linux Mint 21.3 detection to ubuntu.sh
- Set Java version 11 for Linux Mint 21.3 compatibility
- Configured Gazebo Harmonic installation using Ubuntu Jammy repositories for Linux Mint 21.3
- Updated from Garden to Harmonic based on contributor feedback for better compatibility
- Cleaned up branch for cleaner commit history as suggested by reviewers

### Changelog Entry
For release notes:
```
Bugfix: Added Linux Mint 21.3 support to ubuntu.sh installation script with Gazebo Harmonic
Documentation: No changes needed
```

### Test coverage
- Tested on Linux Mint 21.3
- Successfully installed all dependencies including Java 11 and Gazebo Harmonic
- Verified working with PX4 SITL simulation

### Context
The changes ensure proper detection of Linux Mint 21.3 and installation of correct dependencies, allowing PX4 development environment setup on Linux Mint 21.3 systems.

The modifications maintain compatibility with existing Ubuntu installations while adding support for Linux Mint 21.3 users. Changed to Gazebo Harmonic as recommended for better compatibility with Linux Mint's Ubuntu Jammy base.

2024-12-13 13:23 UTC, mrpollo commented
Hey @asifpatankar thanks for the pr, however, we purposely removed specific support for 20.04 & 18.04, going forward we will only carry support for the latest Ubuntu LTS and one version prior, right now its Ubuntu 24.04 & 22.04. 

Regarding Mint, after a quick search i can see the latest release is 22 which corresponds to Ubuntu 24.04, and 21 which is based on Ubuntu 22.04.

With this in mind, its not clear why you are adding support for older Ubuntu versions? it seems like you are restoring lines of code that were previously removed in #23937

2024-12-13 13:24 UTC, mrpollo requested changes
Please see my comments

2024-12-16 13:13 UTC, MaEtUgR requested changes
It seems many improvements get reverted.

Are the essentials still the same as in https://github.com/PX4/PX4-Autopilot/pull/23203 ?

2024-12-16 13:13 UTC, MaEtUgR commented on Tools/setup/ubuntu.sh
> -		gcc-arm-none-eabi \
You're reverting multiple improvements of https://github.com/PX4/PX4-Autopilot/pull/23869

2024-12-16 13:13 UTC, MaEtUgR commented on Tools/setup/ubuntu.sh
> -if [[ "$(printf '%s\n' "$REQUIRED_VERSION" "$PYTHON_VERSION" | sort -V | head -n1)" == "$REQUIRED_VERSION" ]]; then
You're reverting multiple improvements of https://github.com/PX4/PX4-Autopilot/pull/23937

2024-12-16 13:13 UTC, MaEtUgR commented on Tools/setup/ubuntu.sh
> +		gazebo_packages="gz-harmonic"
I'm confused `gazebo_packages="gz-harmonic` is also the else case you delete below. What's the required difference now?

2024-12-17 06:02 UTC, asifpatankar commented
I got the whole scenario. I will delete this branch. Thank you all for all the support and quick responses^^

2024-12-17 06:08 UTC, closed without merging