Scale obstacle distance with vehicle attitude for varying sensor orientations (Collision Prevention)
PX4/PX4-Autopilot pull request #24107
Opened 2024-12-13 14:45 UTC by mahimayoga

### Solved Problem

Scaling of distance_reading to an obstacle was done under the assumption that the sensor was always mounted facing forward, so distance_reading was only scaled for pitch. 

### Solution

Orientation of sensor w.r.t vehicle body frame is taken into account, and the relevant vehicle attitude angles (pitch and/or roll) are used to scale the outputted distance. 

### Changelog Entry
For release notes:
```
Feature: Obstacle distance in obstacle_distance_fused scaled for pitch/roll, based on the orientation of the sensor in the XY plane of the vehicle. 

```

### Alternatives
We could also ...

### Test coverage

- Simulation/hardware testing logs: (Indoor, giving pitch/roll input for different sensor orientations) 
- Front facing: 
![attitude](https://github.com/user-attachments/assets/d58e06b2-c91c-4c6f-8f0f-3f581361edb3)
![distance](https://github.com/user-attachments/assets/a8d1d33a-70d8-4e4a-b064-d19a686562db)

- Left facing (270 deg):

![attitude](https://github.com/user-attachments/assets/4ecf279e-7336-48dc-ba92-8053b5e873da)
![distance](https://github.com/user-attachments/assets/c3069c71-1cf8-4d7e-a920-ffeeae406437)

- 45 deg: 

![attitude](https://github.com/user-attachments/assets/f0656512-14ee-480f-b6f1-0e98b9079da8)
![distance](https://github.com/user-attachments/assets/649e3873-515f-40ce-bca3-a1297399b416)

Roll scaling not super accurate in the 45deg case, probably because the placement of the sensor wasn't very exact. Can see it works well in the Left facing scenario.

2024-12-13 17:04 UTC, bresch reviewed
This looks ok, but there is a more efficient way to do this without passing by euler angles. You can compensate for a tilt by taking the last element of https://github.com/PX4/PX4-Autopilot/blob/4db55cd25fe8ec67e2796b5116a87b1630bab763/src/lib/matrix/matrix/Quaternion.hpp#L521-L541 , which is the length of the projection of the body_z vector on the "down" vector.

2024-12-16 10:44 UTC, mahimayoga commented
> This looks ok, but there is a more efficient way to do this without passing by euler angles. You can compensate for a tilt by taking the last element of
> 
> https://github.com/PX4/PX4-Autopilot/blob/4db55cd25fe8ec67e2796b5116a87b1630bab763/src/lib/matrix/matrix/Quaternion.hpp#L521-L541
> 
> , which is the length of the projection of the body_z vector on the "down" vector.

Thanks! I am having a look now, but it's not intuitive to me how I could use this. I don't know if I am misinterpreting it but: Say I have a forward facing sensor, and I compute the quaternion of the rotated sensor (from the vehicle attitude) w.r.t the initial vehicle frame (FRD). Then taking the last element of `quaternion.dcm_z()` as the scaling factor would also account for tilt in the roll axis right? But this shouldn't affect the distance to an obstacle.

2024-12-16 16:27 UTC, mahimayoga commented
Projection now found without passing Euler angles. Results for sensor placed with 45 degree orientation: 

![attitude_2](https://github.com/user-attachments/assets/c705cf3d-65cc-4182-b4da-c2e9f6488063)
![distance_2](https://github.com/user-attachments/assets/4296878e-49a9-4361-8853-1d9d186ab37b)

2024-12-17 08:52 UTC, bresch commented on src/lib/collision_prevention/CollisionPrevention.cpp
> +		Quatf q_sensor           = Quatf(Eulerf(0.0f, 0.0f, sensor_yaw_body_rad));
To reduce the amount of operations, you can even shortcut this by doing: 
`Quatf q_sensor(cosf(sensor_yaw_body_rad / 2.f), 0.f, 0.f, sinf(sensor_yaw_body_rad / 2.f));`

2024-12-19 10:37 UTC, mahimayoga commented
https://review.px4.io/plot_app?log=777e5193-7f40-40f5-a52d-d4f6fb519eba

Log for flight test today with 45 degree mounted sensor, everything seems to work fine, no weird behaviour.

2024-12-19 15:58 UTC, bresch requested changes

2024-12-19 15:58 UTC, bresch commented on src/drivers/distance_sensor/lightware_laser_i2c/lightware_laser_i2c.cpp
> +	// cli.rotation = (Rotation)distance_sensor_s::ROTATION_LEFT_FACING;
```suggestion
```
We don't need this, if we want to change the rotation we should add a parameter for it.

2024-12-19 15:58 UTC, bresch commented on src/drivers/distance_sensor/lightware_laser_i2c/lightware_laser_i2c.cpp
> +	// cli.rotation = (Rotation)distance_sensor_s::ROTATION_CUSTOM;
```suggestion
```

2024-12-19 15:58 UTC, bresch commented on src/drivers/distance_sensor/lightware_laser_i2c/lightware_laser_i2c.cpp
> +
```suggestion
```
this creates just unnecessary diff

2024-12-20 07:44 UTC, mahimayoga commented on src/lib/collision_prevention/CollisionPrevention.hpp
> -
`#pragma onnce` and including float?

2024-12-20 08:43 UTC, bresch requested changes

2024-12-20 08:43 UTC, bresch commented on src/lib/collision_prevention/CollisionPrevention.cpp
> +		matrix::Vector3f forward_vector(1.0f, 0.0f, 0.0f);
with
```suggestion
		const Vector3f forward_vector(1.0f, 0.0f, 0.0f);
```

with [this](https://github.com/PX4/PX4-Autopilot/blob/7cdf8eee116b5e5cdaef56b216febd2e360d5748/src/lib/collision_prevention/CollisionPrevention.cpp#L43) on top of the cpp file you don't need to specify that Vector2f and Vector3f are from the matrix namespace.

Also, it's not mandatory but I usually find that adding `const` to all those intermediate variables makes it clearer that they're not modified later.

2024-12-20 08:43 UTC, bresch commented on src/lib/collision_prevention/CollisionPrevention.hpp
> -
I just wanted to say that removing the newline was not necessary because it was the only change you made in this file.

2024-12-20 09:14 UTC, bresch requested changes

2024-12-20 09:14 UTC, bresch commented on src/lib/collision_prevention/CollisionPrevention.cpp
> +		float sensor_dist_scale = rotated_sensor_vector_xy.norm();
```suggestion
		const Vector2f rotated_sensor_vector_xy(rotated_sensor_vector(0), rotated_sensor_vector(1));

		const float sensor_dist_scale = rotated_sensor_vector.xy().norm();
```

2024-12-20 13:15 UTC, bresch approved these changes

2024-12-20 13:17 UTC, bresch commented
```
error: local copy 'q_vehicle_attitude' of the variable 'vehicle_attitude' is never modified; consider avoiding the copy [performance-unnecessary-copy-initialization,-warnings-as-errors]
                const Quatf q_vehicle_attitude(vehicle_attitude);
```
`vehicle_attitude` is already a quaternion

2024-12-20 13:46 UTC, bresch approved these changes

2024-12-20 13:47 UTC, merged