Message versioning and translation for ROS
PX4/PX4-Autopilot pull request #24113
Opened 2024-12-16 09:10 UTC by bkueng

Follow-up to https://github.com/PX4/PX4-Autopilot/pull/23850

- adds versioning to the topic name in the uxrce dds client
- adds a translation node that runs under ROS and converts between different versions of a topic (see [this document](https://docs.google.com/document/u/1/d/18_RxV1eEjt4haaa5QkFZAlIAJNv9w5HED2aUEiG7PVQ/edit?tab=t.0) for details)
- adds CI to ensure whenever a versioned topic changes, a new version is added. The required steps are documented in this [README](https://github.com/PX4/PX4-Autopilot/compare/message_versioning_and_translation#diff-4b3d84ca3a149ca981309a34c37315a37bd245bc617efb9644a74d2fb74024d3). We can also move that to a PX4 docs page.
- adds CI for the ROS translation node

I ended up adding a script that copies the translation node and msg files into a ROS workspace. I tested an approach of directly adding PX4 into a workspace, but ran into too many issues (e.g. msg namespace cannot be customized independently, or that there cannot be multiple subprojects if the toplevel directory already contains a CMakeLists.txt).

2025-01-13 08:58 UTC, bastianhjaeger commented on msg/translation_node/README.md
> +  Update the existing translations that use the current topic version to the now old version.
```
Update the existing translations that use the current topic version to the now old version.
```
How/where shall this be done?

2025-01-14 06:18 UTC, bkueng commented on msg/translation_node/README.md
> +  Update the existing translations that use the current topic version to the now old version.
This is now described in more depth in https://github.com/PX4/PX4-user_guide/pull/3465. I'll remove it from here and link to that instead.

2025-01-29 10:31 UTC, GuillaumeLaine approved these changes
Works as advertised, this is awesome 👍🏻

2025-01-31 10:00 UTC, mrpollo requested changes
i left a few nitpicky comments regarding CI @bkueng, overall great work

2025-01-31 10:00 UTC, mrpollo commented on .github/workflows/ros_translation_node.yml
> +    runs-on: ubuntu-latest
Given how this build is taking longer than 5min I suggest and running on every PR + push to main, I suggest we move this to our AWS infra

```suggestion
    runs-on: [runs-on,runner=8cpu-linux-x64,image=ubuntu24-full-x64,"run-id=${{ github.run_id }}",spot=false]
```

2025-01-31 10:00 UTC, mrpollo commented on .github/workflows/ros_translation_node.yml
> +name: ROS translation node tests
Given how actions works, the name we use the first time will stay forever, so we might as well capitalize the title.

```suggestion
name: ROS Translation Node Tests
```

2025-01-31 10:00 UTC, mrpollo commented on .github/workflows/ros_translation_node.yml
> +name: ROS translation node tests
Do we ever expect to test against multiple ROS versions? if so should we mark this as ROS Humble?

2025-02-04 08:37 UTC, bkueng commented on .github/workflows/ros_translation_node.yml
> +    runs-on: ubuntu-latest
Thanks, I updated that

2025-02-04 08:38 UTC, bkueng commented on .github/workflows/ros_translation_node.yml
> +name: ROS translation node tests
Yes we can run this against a matrix of ROS versions. I started off with Humble for now, but if you prefer I can add others as well.

2025-02-04 08:46 UTC, mrpollo commented on .github/workflows/ros_translation_node.yml
> +name: ROS translation node tests
Perhaps we should have decided which ROS versions we support so we can update CI everywhere. For this PR, whoever, perhaps it's best to introduce the matrix and add at least two versions of ROS.

2025-02-05 10:40 UTC, bkueng commented on .github/workflows/ros_translation_node.yml
> +name: ROS translation node tests
I added Jazzy

2025-02-05 10:41 UTC, bkueng commented
Thanks for all the reviews and tests. This is getting ready.

2025-02-07 09:13 UTC, sfuhrer commented
@mrpollo good to go from your side?
This PR is required to unblock development on PX4 that touches uorb topics, so would be good if we can wrap it up asap.

2025-02-07 15:30 UTC, mrpollo approved these changes

2025-02-07 15:31 UTC, mrpollo commented
Good to go

2025-02-11 12:19 UTC, merged