sbgecom: Implement sbgECom INS driver
PX4/PX4-Autopilot pull request #24137
Opened 2024-12-19 19:33 UTC by tolesam

# New Feature

Implement sbgECom messages handling to provide IMU sensors, GNSS and EKF data to the autopilot
Be able to parametrize the serial port, baudrate and the communicating mode
Clone sbgECom library only if sbgecom support is enabled and apply a patch
Be able to send SBG Systems INS settings in several ways when starting sbgecom driver

# Bug Fixes

Fix sensor airspeed simulator units 
Fix HIGHRES_IMU pressure unit

# Remarks

Users of external INS (vectornav and sbgecom) need to enable the drivers in the config. As all external INS are currently enabled on some board config, CI is failing.

2024-12-20 18:52 UTC, tolesam commented
Hello,
Can someone help me to understand what is the issue with the failing builds?
The sbgECom driver is not built by default and the two minor fixes I did should not have any significant impact on the FLASH.
Thanks in advance.

2024-12-21 13:24 UTC, tolesam commented
> Hello @tolesam I have a question. Does this PR intend to be used with the Ellipse Series, Ellipse 2 Micro Series, or both?
> 
> I'm interested in SBG products.

Hello @saengphet,
It's intended to be used with all SBG Systems' INS products.
Feel free to give us any feedback about it, we'll be happy to help you with our products' integration with this driver.
Regards,
Samuel Toledano

2025-01-10 16:54 UTC, tolesam commented
Hi @dagar ,

Can you take a look at this PR please?
I see you've already integrated another INS driver and we would be happy to have sbgecom driver available on PX4 firmware as well.

Moreover, it seems the job "Build and Push Container" doesn't work on PRs, do you have any idea why?
I tried to run it locally on ubuntu-latest and it worked well.

Thanks in advance.

2025-01-15 14:18 UTC, bresch requested changes

2025-01-15 14:18 UTC, bresch commented on src/drivers/ins/sbgecom/sbgecom.patch
> +diff --git a/CMakeLists.txt b/CMakeLists.txt
I guess you didn't intended to commit this patch file

2025-01-27 15:59 UTC, tolesam commented on src/drivers/ins/sbgecom/sbgecom.patch
> +diff --git a/CMakeLists.txt b/CMakeLists.txt
@bresch Should I resolve the conversation or is it up to you?

2025-02-17 10:30 UTC, tolesam commented
Hello @bresch ,
Do you have any feedback about this PR or is there anything I can do to help move it forward?
Thanks in advance for your review.

2025-02-17 12:41 UTC, bresch commented on src/modules/simulation/sensor_airspeed_sim/SensorAirspeedSim.cpp
> +			const float alt_amsl = gpos.alt / 1000.0f; // mm to m
vehicle_global_position.alt is already in meters

2025-02-17 12:52 UTC, bresch commented on boards/cubepilot/cubeorange/default.px4board
> -CONFIG_COMMON_INS=y
This would break existing setups using the vector nav driver. I understand you cannot leave it enabled as both drivers won't fit flash but maybe add a note in the PR description for the release notes that users of external INS (vector nav and sbgecom) need to enable the drivers in the config.

2025-02-17 18:12 UTC, tolesam commented on src/modules/sensors/vehicle_imu/VehicleIMU.cpp
> -			if (accel.timestamp < accel.timestamp_sample) {
When using an external INS that is not powered by the autopilot, if it is started beforehand, it causes errors.

2025-02-17 18:13 UTC, tolesam commented on boards/cubepilot/cubeorange/default.px4board
> -CONFIG_COMMON_INS=y
Ok, I revert it and change the PR description.

2025-02-18 09:21 UTC, tolesam commented on boards/cubepilot/cubeorange/default.px4board
> -CONFIG_COMMON_INS=y
@bresch By reverting this change the issue is I have 3 jobs that are failing due to flash overflowing.

2025-02-18 13:44 UTC, bresch commented on src/modules/sensors/vehicle_imu/VehicleIMU.cpp
> -			if (accel.timestamp < accel.timestamp_sample) {
Right, but that shouldn't be fixed by ignoring the problem. From the point of view of the autopilot, it's not possible that the sample was received before it was created. If this is the case, it's because both systems are not time-synced. 

If proper time-sync is not possible, I think we should rather override the `timestamp_sample` in the driver, as having an incorrect `timestamp_sample` is worse than assuming 0 delay between both timestamps.

2025-02-18 13:49 UTC, bresch commented on boards/cubepilot/cubeorange/default.px4board
> -CONFIG_COMMON_INS=y
@dagar do we then just disable all INS drivers?

2025-02-21 23:24 UTC, mrpollo commented
@tolesam can you please rebase your pr with latest from main? I want to see if the failed CI tests are real

2025-02-22 11:44 UTC, tolesam commented
@mrpollo 
Build jobs were failing due to temperature removal from airspeed message.
I've changed it.
Now remaining failing jobs are due to flash overflow.

2025-02-28 10:35 UTC, tolesam commented on boards/cubepilot/cubeorange/default.px4board
> -CONFIG_COMMON_INS=y
@bresch  @dagar  Is there any update about this subject?

2025-03-17 17:46 UTC, tolesam commented on boards/cubepilot/cubeorange/default.px4board
> -CONFIG_COMMON_INS=y
Hello @bresch @dagar 
Is there any update about this subject?

2025-04-30 15:27 UTC, tolesam commented
Hello @bresch ,
Would you have any additional feedback on this PR, or is there anything I can do to help progress it?
Thanks in advance for your time and review.

2025-06-05 13:21 UTC, tolesam commented
Hello @bresch ,
I come back to you about this PR. Is there anything I can do to make it progress?
Moreover, I still have a job failing due too invalid signature:
`Err:1 http://packages.ros.org/ros2/ubuntu focal InRelease
  The following signatures were invalid: EXPKEYSIG F42ED6FBAB17C654 Open Robotics <info@osrfoundation.org>`

2025-06-27 15:37 UTC, tolesam commented
Hello @bresch @mrpollo @dagar ,
Do you have any additional feedback on this PR, or is there anything I can do to help progress it?
Thanks for CI fix BTW, it work like a charm now.

2025-08-05 11:26 UTC, tolesam commented
Hello @bresch ,
Is there anything blocking this PR? How can I make it progress?

2025-08-05 15:17 UTC, mrpollo commented on src/drivers/ins/sbgecom/sbgecom.patch
> +diff --git a/CMakeLists.txt b/CMakeLists.txt
Hey @tolesam, I appreciate the thoughtful method to fetch the sbgECom only when it's needed; however, it will create a problem for maintainers, since it's the only driver doing this, and we can't deal with special cases as it stands. Can you instead add the submodule, please?

We typically only allow submodules owned by the PX4 organization. Here's the link to the fork of the repository https://github.com/PX4/sbgECom

2025-08-05 16:27 UTC, tolesam commented
@mrpollo 
I understand, I've changed it to use submodule instead.

2025-08-05 17:48 UTC, mrpollo commented
@tolesam, can you also look into removing the patch strategy?

2025-08-07 02:59 UTC, hamishwillee reviewed
The docs changes for this are good - can't comment on the rest. 

@tolesam FYI I much prefer it if PRs are opened for maintainer edits. There are minor changes I might otherwise make that will now have to go into the tree and be fixed later.

2025-08-07 08:04 UTC, tolesam commented
> The docs changes for this are good - can't comment on the rest.
> 
> @tolesam FYI I much prefer it if PRs are opened for maintainer edits. There are minor changes I might otherwise make that will now have to go into the tree and be fixed later.

Unfortunatly, this option doesn't appear on my PR but I have granted you access to the forked repo so you can change whatever you want.
Thanks for your review.

2025-08-07 08:41 UTC, tolesam commented
> @tolesam, can you also look into removing the patch strategy?

@mrpollo 
I removed it and did some change to fit with current main branch.

2025-08-07 16:46 UTC, mrpollo commented
Waiting for https://github.com/PX4/PX4-Autopilot/pull/25389 to come in, so you don't have to commit this in this PR, since this is a cleaner approach since we will likely have to squash your commit history.

2025-08-07 20:06 UTC, hamishwillee commented
> Unfortunately, this option doesn't appear on my PR but I have granted you access to the forked repo so you can change whatever you want. Thanks for your review.

Thank you so much. I'll come back next week. Fighting v1.16 publishing issues. FYI only, I believe the option appears when you create the PR. Could be wrong.

2025-08-08 12:35 UTC, tolesam commented
@mrpollo Great, I've rebased it so board config change is not there anymore.

2025-08-12 17:39 UTC, mrpollo commented
@tolesam did you mean to keep the `*.patch` file?

2025-08-13 00:37 UTC, hamishwillee commented on src/drivers/ins/sbgecom/CMakeLists.txt
> +#   Copyright (c) 2022 PX4 Development Team. All rights reserved.
Fix the dates up.

2025-08-13 00:39 UTC, hamishwillee approved these changes
Approving for the docs part.

2025-08-13 08:46 UTC, tolesam commented
> @tolesam did you mean to keep the `*.patch` file?

@mrpollo I've deleted my previous answer which was wrong. I've deleted the patch file.

2025-08-13 08:46 UTC, tolesam commented on src/drivers/ins/sbgecom/CMakeLists.txt
> +#   Copyright (c) 2022 PX4 Development Team. All rights reserved.
Changed to 2025 in sbgecom.cpp, sbgecom.hpp and CMakeLists.txt.

2025-08-18 11:46 UTC, tolesam commented
@mrpollo 
It should be good now.
There's still one failing job, I think it's because of missing parameters in the doc but I was told there's a script to update them after merge. Is that correct?

2025-09-02 08:17 UTC, tolesam commented
Hi @mrpollo , @bresch ,
Is there any update about this PR on your side?
Thanks in advance for the review and your time.

2025-09-08 13:34 UTC, tolesam commented
Hi @mrpollo , @bresch ,
Is there any update about this PR on your side?
Thanks in advance for the review and your time.

2025-09-10 19:31 UTC, dakejahl approved these changes

2025-09-10 19:31 UTC, dakejahl commented on src/drivers/drv_sensor.h
> +#define DRV_INS_DEVTYPE_SBG		0xEB
```suggestion
#define DRV_INS_DEVTYPE_SBG		0xEC
```

2025-09-11 08:22 UTC, tolesam commented
@dakejahl 
Thank you for your review and approval yesterday, I've updated this branch with your suggestion and rebased it to fix doc check job which was failing.

2025-09-11 08:32 UTC, hamishwillee commented
The docs flaws can be ignored - they will be fixed in post process. The macOS flaws may be real. 

@dakejahl You can merge if you are happy - the docs are OK.

2025-09-11 08:37 UTC, merged